#include "hnnx/ops/ops.hpp"
#include "hnnx/ir/op_registry.hpp"
#include "hnnx/ir/graph_prepare.hpp"
#include "hnnx/cost/cost_model.hpp"
#include <cmath>
#include <cstring>
#include <memory>
#include <algorithm>
#include <numeric>

namespace hnnx {

void register_hlx_hmx_ops();

// 指令选择: 根据 op 类型 + dtype + SoC 选 HVX/HMX wrapper。
// Source: hvx_wrapper_select.cc, hmx_op_select.cc
// 真实库查 op 是否在 HMX 支持表 + dtype 是否量化 + SoC 是否有 HMX 单元。
HwWrapper select_wrapper(const std::string& op_type, DType dtype, uint32_t soc_type) {
    // HMX 适合 Conv/MatMul 等密集矩阵运算 (v73+ 有 HMX)
    bool is_matrix_op = (op_type == "Conv" || op_type == "DepthWiseConv2d" ||
                         op_type == "DilatedConv" || op_type == "GroupedConv" ||
                         op_type == "MatMul" || op_type == "Dense");
    bool hmx_capable = (soc_type >= 73);  // v73+ 有 HMX
    bool quant_dtype = (dtype == DType::Int8 || dtype == DType::Int16 ||
                        dtype == DType::Int4 || dtype == DType::UInt4 ||
                        dtype == DType::FP8_E4M3 || dtype == DType::FP8_E5M2 ||
                        dtype == DType::MXFP4);
    if (is_matrix_op && hmx_capable && quant_dtype) {
        return (dtype == DType::Int4 || dtype == DType::UInt4) ? HwWrapper::HMX_MatrixInt4
                                                              : HwWrapper::HMX_Matrix;
    }
    // HVX 向量内核处理 elementwise/激活/norm 等 (所有 SoC 都有 HVX)
    if (dtype != DType::Float32 && dtype != DType::Float16 && dtype != DType::BFloat16) {
        return HwWrapper::HVX_Vector;
    }
    // 浮点路径在真实库走 HTA 或标量后备; host reimpl 用标量
    return HwWrapper::HVX_Scalar;
}

// TypicalOp::cost: use cost model to estimate
float TypicalOp::cost(const hnnx::Graph* g) const {
    // Source: typical_op_prepare.cc
    if (op_type_name.empty()) return 1.0f;
    static costbased::CostSource cs;
    static bool init = false;
    if (!init) { cs.init_for_soc("v75"); init = true; }
    return cs.get_prediction_from_cost_model(op_type_name, this, nullptr, {});
}

void TypicalOp::serialize_internal(Serializer& ser, int chkpt_type) const {
    // Source: serialize_oplist.cc, Op::serialize_internal @0x10bc690
    // [反汇编证据 libQnnHtp.so v2.48] serialize_op @0x12ec630:
    //   - 标记 0x1303EE71 硬编码 (mov r13d,0x1303ee71 @0x12ec688)
    //   - type 字段 = (extra_info[0x18] >> 6 & 0xf) << 24, 加 HMX/flags 修正
    //     0x01=compute, 0x02=memory, 0x03=sync, 0x04=DMA(DmaCheckpoint), 0x0b=HMX
    //   - block_ref = extra_info[0x24] & 0xFFFFFF | (0x03<<24)
    //   - SET/WAIT (make_dma_checkpoint_op @0xd958d0) 共享 serialize_internal @0xd969a0
    //     → 字节不可区分; 详见 reference/docs/schedule_analysis.md
    // In the real binary each Op writes its own record here. In this
    // reimplementation the runlist writer (GraphPrepare::serialize_opdef, driven
    // by do_serialize) emits one TAG_OP_RECORD per op from the OpDef, which
    // carries the full graph structure; the execution Op is regenerated by the
    // op factory at load time. This hook is therefore a no-op: the serializer
    // is driven by the graph, not by individual Op instances.
    (void)ser; (void)chkpt_type;
}

// TypicalOp::execute (3-arg): delegate to 4-arg with empty in_defs
void TypicalOp::execute(const std::vector<const uint8_t*>& inputs,
                        uint8_t* output,
                        const OutputDef& out_def) const {
    execute(inputs, output, out_def, {});
}

// TypicalOp::execute (4-arg, with input OutputDefs): host-side reference 实现 (D 阶段)。
// 按 op_type_name 分派到对应的数值内核。inputs/outputs 是扁平字节缓冲，
// 假设 Float32 布局 (真实库按 dtype/wrapper 选量化内核，这里用浮点参考)。
// output_def.dims 描述输出形状; 元素数 = dims 乘积。
// in_defs 提供各输入的 OutputDef, 供 MatMul 等需要输入形状的 op 使用。
// 这是 correctness reference, 非性能路径。
void TypicalOp::execute(const std::vector<const uint8_t*>& inputs,
                        uint8_t* output,
                        const OutputDef& out_def,
                        const std::vector<OutputDef>& in_defs) const {
    if (!output) return;
    float* out = reinterpret_cast<float*>(output);
    // 输出元素数
    size_t n = 1;
    for (uint32_t i = 0; i < out_def.rank && i < 5; ++i)
        n *= static_cast<size_t>(out_def.dims[i]);
    if (n == 0) n = 1;

    const auto in_float = [&](size_t idx, size_t i) -> float {
        if (idx >= inputs.size() || !inputs[idx]) return 0.0f;
        return reinterpret_cast<const float*>(inputs[idx])[i];
    };

    if (op_type_name == "Relu" || op_type_name == "ConvActivations") {
        // Relu: max(0, x); ConvActivations (post-fusion): 同 Relu 语义对第一个输入
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        for (size_t i = 0; i < n; ++i) out[i] = in0 ? std::max(0.0f, in0[i]) : 0.0f;
    } else if (op_type_name == "Add") {
        for (size_t i = 0; i < n; ++i) out[i] = in_float(0, i) + in_float(1, i);
    } else if (op_type_name == "Sub") {
        for (size_t i = 0; i < n; ++i) out[i] = in_float(0, i) - in_float(1, i);
    } else if (op_type_name == "Mul") {
        for (size_t i = 0; i < n; ++i) out[i] = in_float(0, i) * in_float(1, i);
    } else if (op_type_name == "Div") {
        for (size_t i = 0; i < n; ++i) {
            float d = in_float(1, i);
            out[i] = (d != 0.0f) ? in_float(0, i) / d : 0.0f;
        }
    } else if (op_type_name == "Sigmoid") {
        for (size_t i = 0; i < n; ++i) out[i] = 1.0f / (1.0f + std::exp(-in_float(0, i)));
    } else if (op_type_name == "Tanh") {
        for (size_t i = 0; i < n; ++i) out[i] = std::tanh(in_float(0, i));
    } else if (op_type_name == "Exp") {
        for (size_t i = 0; i < n; ++i) out[i] = std::exp(in_float(0, i));
    } else if (op_type_name == "Neg") {
        for (size_t i = 0; i < n; ++i) out[i] = -in_float(0, i);

    // ── Math ops (elementwise, single/dual input) ──
    } else if (op_type_name == "Power") {
        for (size_t i = 0; i < n; ++i) out[i] = std::pow(in_float(0, i), in_float(1, i));
    } else if (op_type_name == "Log") {
        for (size_t i = 0; i < n; ++i) { float v = in_float(0, i); out[i] = (v > 0) ? std::log(v) : 0.0f; }
    } else if (op_type_name == "Sqrt") {
        for (size_t i = 0; i < n; ++i) { float v = in_float(0, i); out[i] = (v >= 0) ? std::sqrt(v) : 0.0f; }
    } else if (op_type_name == "Rsqrt") {
        for (size_t i = 0; i < n; ++i) { float v = in_float(0, i); out[i] = (v > 0) ? 1.0f/std::sqrt(v) : 0.0f; }
    } else if (op_type_name == "Abs") {
        for (size_t i = 0; i < n; ++i) out[i] = std::fabs(in_float(0, i));
    } else if (op_type_name == "Ceiling") {
        for (size_t i = 0; i < n; ++i) out[i] = std::ceil(in_float(0, i));
    } else if (op_type_name == "Floor") {
        for (size_t i = 0; i < n; ++i) out[i] = std::floor(in_float(0, i));
    } else if (op_type_name == "Round") {
        for (size_t i = 0; i < n; ++i) out[i] = std::round(in_float(0, i));
    } else if (op_type_name == "Sin") {
        for (size_t i = 0; i < n; ++i) out[i] = std::sin(in_float(0, i));
    } else if (op_type_name == "Cos") {
        for (size_t i = 0; i < n; ++i) out[i] = std::cos(in_float(0, i));
    } else if (op_type_name == "SquaredDifference") {
        for (size_t i = 0; i < n; ++i) { float d = in_float(0,i) - in_float(1,i); out[i] = d*d; }

    // ── Activation ops ──
    } else if (op_type_name == "Gelu") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = 0.5f * x * (1.0f + std::erf(x * 0.7071067811865475f));
        }
    } else if (op_type_name == "LeakyRelu") {
        float alpha = 0.01f;
        if (params.size() >= 4) std::memcpy(&alpha, params.data(), 4);
        for (size_t i = 0; i < n; ++i) { float x = in_float(0,i); out[i] = x >= 0 ? x : alpha*x; }
    } else if (op_type_name == "Elu") {
        float alpha = 1.0f;
        if (params.size() >= 4) std::memcpy(&alpha, params.data(), 4);
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = x >= 0 ? x : alpha * (std::exp(x) - 1.0f);
        }
    } else if (op_type_name == "Swish") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = x / (1.0f + std::exp(-x));
        }
    } else if (op_type_name == "HardSigmoid") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = std::max(0.0f, std::min(1.0f, x * 0.2f + 0.5f));
        }
    } else if (op_type_name == "HardSwish") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = x * std::max(0.0f, std::min(1.0f, x * 0.2f + 0.5f));
        }
    } else if (op_type_name == "Softplus") {
        for (size_t i = 0; i < n; ++i) out[i] = std::log(1.0f + std::exp(in_float(0, i)));
    } else if (op_type_name == "Clamp") {
        float lo = -1e30f, hi = 1e30f;
        if (params.size() >= 8) { std::memcpy(&lo, params.data(), 4); std::memcpy(&hi, params.data()+4, 4); }
        for (size_t i = 0; i < n; ++i) out[i] = std::max(lo, std::min(hi, in_float(0, i)));
    } else if (op_type_name == "MinMax") {
        // MinMax: element-wise min of two inputs
        for (size_t i = 0; i < n; ++i) out[i] = std::min(in_float(0,i), in_float(1,i));

    // ── Shape ops ──
    } else if (op_type_name == "Reshape" || op_type_name == "Flatten") {
        // Data layout unchanged; just copy elements
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (in0) { std::memcpy(out, in0, n * sizeof(float)); }
        else { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; }
    } else if (op_type_name == "Transpose") {
        // Transpose: permute dimensions.  inputs[0]=data, inputs[1]=perm (int32)
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; }
        else {
            uint32_t rank = out_def.rank;
            std::vector<uint32_t> out_dims(rank), perm(rank);
            for (uint32_t d = 0; d < rank; d++) out_dims[d] = out_def.dims[d];
            // Read perm from second input or from params
            if (inputs.size() > 1 && inputs[1]) {
                const int32_t* p = reinterpret_cast<const int32_t*>(inputs[1]);
                for (uint32_t d = 0; d < rank; d++) perm[d] = static_cast<uint32_t>(p[d]);
            } else {
                for (uint32_t d = 0; d < rank; d++) perm[d] = rank - 1 - d;
            }
            // Compute input shape from in_defs or infer from output + perm
            std::vector<uint32_t> in_dims(rank);
            if (!in_defs.empty()) {
                for (uint32_t d = 0; d < rank && d < in_defs[0].rank; d++)
                    in_dims[d] = in_defs[0].dims[d];
            } else {
                for (uint32_t d = 0; d < rank; d++) in_dims[d] = out_dims[perm[d]];
            }
            // Strides for input linear indexing
            std::vector<size_t> in_strides(rank, 1);
            for (int d = (int)rank - 2; d >= 0; d--)
                in_strides[d] = in_strides[d+1] * in_dims[d+1];
            for (size_t i = 0; i < n; ++i) {
                size_t rem = i;
                size_t src = 0;
                for (uint32_t d = 0; d < rank; d++) {
                    size_t coord = rem / (d+1 < rank ? [&]{ size_t s=1; for(uint32_t k=d+1;k<rank;k++) s*=out_dims[k]; return s; }() : 1);
                    rem %= (d+1 < rank ? [&]{ size_t s=1; for(uint32_t k=d+1;k<rank;k++) s*=out_dims[k]; return s; }() : 1);
                    src += coord * in_strides[perm[d]];
                }
                out[i] = (src < n) ? in0[src] : 0.0f;
            }
        }
    } else if (op_type_name == "Concat") {
        // Concat: join inputs along axis.  axis from params or default last.
        int axis = -1;
        if (params.size() >= 4) { int32_t a; std::memcpy(&a, params.data(), 4); axis = a; }
        uint32_t rank = out_def.rank;
        if (axis < 0) axis += rank;
        if (axis < 0) axis = (int)rank - 1;
        // Outer = product of dims before axis, inner = product after axis
        size_t outer = 1, inner = 1;
        for (int d = 0; d < axis; d++) outer *= out_def.dims[d];
        for (uint32_t d = (uint32_t)axis + 1; d < rank; d++) inner *= out_def.dims[d];
        size_t out_axis = out_def.dims[axis];
        size_t off = 0;
        for (size_t idx = 0; idx < inputs.size(); idx++) {
            if (!inputs[idx]) continue;
            size_t in_axis_len = 0;
            if (idx < in_defs.size() && in_defs[idx].rank > (uint32_t)axis)
                in_axis_len = in_defs[idx].dims[axis];
            else in_axis_len = out_axis / std::max<size_t>(1, inputs.size());
            const float* src = reinterpret_cast<const float*>(inputs[idx]);
            for (size_t o = 0; o < outer; o++) {
                for (size_t a = 0; a < in_axis_len; a++) {
                    for (size_t j = 0; j < inner; j++) {
                        out[o * out_axis * inner + (off + a) * inner + j] =
                            src[o * in_axis_len * inner + a * inner + j];
                    }
                }
            }
            off += in_axis_len;
        }

    // ── Pooling ──
    } else if (op_type_name == "AvgPool" || op_type_name == "MaxPool") {
        // NHWC: input [N,H,W,C], output [N,Ho,Wo,C]
        // Infer pool/stride from shapes; assume pad=0
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; }
        else {
            size_t N_b = (out_def.rank >= 4) ? out_def.dims[0] : 1;
            size_t Ho = (out_def.rank >= 4) ? out_def.dims[1] : 1;
            size_t Wo = (out_def.rank >= 4) ? out_def.dims[2] : 1;
            size_t C  = (out_def.rank >= 4) ? out_def.dims[3] : out_def.dims[out_def.rank-1];
            size_t Hi = (!in_defs.empty() && in_defs[0].rank >= 4) ? in_defs[0].dims[1] : Ho;
            size_t Wi = (!in_defs.empty() && in_defs[0].rank >= 4) ? in_defs[0].dims[2] : Wo;
            size_t sh = (Ho > 1) ? (Hi - 1) / Ho + 1 : 1;
            size_t sw = (Wo > 1) ? (Wi - 1) / Wo + 1 : 1;
            size_t kh = Hi - (Ho - 1) * sh;
            size_t kw = Wi - (Wo - 1) * sw;
            if (kh == 0) kh = 1;
            if (kw == 0) kw = 1;
            bool is_max = (op_type_name == "MaxPool");
            for (size_t nb = 0; nb < N_b; nb++)
              for (size_t ho = 0; ho < Ho; ho++)
                for (size_t wo = 0; wo < Wo; wo++)
                  for (size_t c = 0; c < C; c++) {
                    float val = is_max ? -1e30f : 0.0f;
                    size_t cnt = 0;
                    for (size_t kh_ = 0; kh_ < kh; kh_++)
                      for (size_t kw_ = 0; kw_ < kw; kw_++) {
                        size_t hi = ho*sh + kh_, wi = wo*sw + kw_;
                        if (hi < Hi && wi < Wi) {
                            float v = in0[((nb*Hi + hi)*Wi + wi)*C + c];
                            val = is_max ? std::max(val, v) : val + v;
                            cnt++;
                        }
                      }
                    if (!is_max && cnt > 0) val /= cnt;
                    out[((nb*Ho + ho)*Wo + wo)*C + c] = val;
                  }
        }

    // ── Normalization ──
    } else if (op_type_name == "BatchNorm" || op_type_name == "LayerNorm" ||
               op_type_name == "RmsNorm" || op_type_name == "InstanceNorm" ||
               op_type_name == "GroupNorm") {
        // Generic normalization: inputs[0]=data, inputs[1]=scale, inputs[2]=bias
        // For host reference: normalize to zero-mean/unit-variance, then scale+bias
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        const float* scale = (inputs.size() > 1) ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        const float* bias  = (inputs.size() > 2) ? reinterpret_cast<const float*>(inputs[2]) : nullptr;
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; }
        else {
            // Determine group size: last dim for per-channel norm
            size_t C = (out_def.rank >= 1) ? out_def.dims[out_def.rank - 1] : 1;
            size_t groups = n / C;
            if (groups == 0) groups = 1;
            for (size_t g = 0; g < groups; g++) {
                float mean = 0;
                for (size_t c = 0; c < C; c++) mean += in0[g*C + c];
                mean /= C;
                float var = 0;
                for (size_t c = 0; c < C; c++) { float d = in0[g*C+c] - mean; var += d*d; }
                var /= C;
                float inv = 1.0f / std::sqrt(var + 1e-5f);
                for (size_t c = 0; c < C; c++) {
                    float v = (in0[g*C+c] - mean) * inv;
                    if (scale) v *= scale[c % C];
                    if (bias) v += bias[c % C];
                    out[g*C + c] = v;
                }
            }
        }
    } else if (op_type_name == "Softmax") {
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; return; }
        float mx = in0[0];
        for (size_t i = 1; i < n; ++i) if (in0[i] > mx) mx = in0[i];
        float sum = 0.0f;
        for (size_t i = 0; i < n; ++i) { out[i] = std::exp(in0[i] - mx); sum += out[i]; }
        if (sum > 0) for (size_t i = 0; i < n; ++i) out[i] /= sum;
    } else if (op_type_name == "MatMul" || op_type_name == "Dense") {
        // MatMul: C[m,n] = A[m,k] @ B[k,n]
        // in_defs[0] = A shape [m,k], in_defs[1] = B shape [k,n]
        // output_def.dims = [m, n]
        const float* A = inputs.size() > 0 ? reinterpret_cast<const float*>(inputs[0]) : nullptr;
        const float* B = inputs.size() > 1 ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        if (!A || !B) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; return; }
        // Determine m, n from output_def; k from input shapes.
        // After batch-dim padding, rank-2 matrices [m,n] become [1,1,m,n].
        // Always use the LAST two dimensions for the matrix shape.
        size_t m = (out_def.rank >= 2) ? out_def.dims[out_def.rank - 2] : 1;
        size_t nn = (out_def.rank >= 1) ? out_def.dims[out_def.rank - 1] : n;
        size_t k = 0;
        // Prefer: k from B's second-to-last dim (B is [..., k, n])
        if (in_defs.size() > 1 && in_defs[1].rank >= 2 && in_defs[1].dims[in_defs[1].rank - 2] > 0) {
            k = in_defs[1].dims[in_defs[1].rank - 2];
        } else if (in_defs.size() > 0 && in_defs[0].rank >= 2 && in_defs[0].dims[in_defs[0].rank - 1] > 0) {
            k = in_defs[0].dims[in_defs[0].rank - 1];
        } else if (m > 0) {
            k = m;
        }
        if (k == 0) k = 1;
        for (size_t i = 0; i < m; ++i) {
            for (size_t j = 0; j < nn; ++j) {
                float acc = 0.0f;
                for (size_t p = 0; p < k; ++p) {
                    acc += A[i * k + p] * B[p * nn + j];
                }
                out[i * nn + j] = acc;
            }
        }
    } else if (op_type_name == "Conv" || op_type_name == "DepthWiseConv2d") {
        // Conv2D host reference: NHWC layout
        // inputs[0] = input [N, Hi, Wi, Cin]
        // inputs[1] = weight [Kh, Kw, Cin, Cout] (standard Conv)
        //             or [Kh, Kw, 1, Cin] (depthwise)
        // inputs[2] = bias [Cout] (optional)
        const float* inp    = inputs.size() > 0 ? reinterpret_cast<const float*>(inputs[0]) : nullptr;
        const float* weight = inputs.size() > 1 ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        const float* bias   = inputs.size() > 2 ? reinterpret_cast<const float*>(inputs[2]) : nullptr;
        if (!inp || !weight) {
            for (size_t i = 0; i < n; ++i) out[i] = 0.0f;
        } else {
            // Extract shapes from in_defs and out_def (rank-4 NHWC)
            size_t N_b = (out_def.rank >= 4) ? out_def.dims[0] : 1;
            size_t Ho  = (out_def.rank >= 4) ? out_def.dims[1] : 1;
            size_t Wo  = (out_def.rank >= 4) ? out_def.dims[2] : 1;
            size_t Cout = (out_def.rank >= 4) ? out_def.dims[3] : out_def.dims[out_def.rank-1];
            size_t Hi = (in_defs.size() > 0 && in_defs[0].rank >= 4) ? in_defs[0].dims[1] : Ho;
            size_t Wi = (in_defs.size() > 0 && in_defs[0].rank >= 4) ? in_defs[0].dims[2] : Wo;
            size_t Cin = (in_defs.size() > 0 && in_defs[0].rank >= 4) ? in_defs[0].dims[3] : 1;
            // Kernel size from weight shape (in_defs[1])
            size_t Kh = (in_defs.size() > 1 && in_defs[1].rank >= 4) ? in_defs[1].dims[0] : 1;
            size_t Kw = (in_defs.size() > 1 && in_defs[1].rank >= 4) ? in_defs[1].dims[1] : 1;
            // Infer stride from shapes: Ho = (Hi - Kh)/sh + 1 => sh = (Hi - Kh)/(Ho - 1)
            size_t sh = (Ho > 1) ? (Hi - Kh) / (Ho - 1) : 1;
            size_t sw = (Wo > 1) ? (Wi - Kw) / (Wo - 1) : 1;
            if (sh == 0) sh = 1;
            if (sw == 0) sw = 1;
            bool is_dw = (op_type_name == "DepthWiseConv2d");
            // Compute pad to center the kernel (same padding)
            int pad_h_num = (int)((Ho - 1) * sh + Kh) - (int)Hi;
            int pad_w_num = (int)((Wo - 1) * sw + Kw) - (int)Wi;
            size_t pad_h = (pad_h_num > 0) ? (size_t)pad_h_num / 2 : 0;
            size_t pad_w = (pad_w_num > 0) ? (size_t)pad_w_num / 2 : 0;

            for (size_t nb = 0; nb < N_b; nb++)
              for (size_t ho = 0; ho < Ho; ho++)
                for (size_t wo = 0; wo < Wo; wo++)
                  for (size_t co = 0; co < Cout; co++) {
                    float acc = bias ? bias[co] : 0.0f;
                    for (size_t kh = 0; kh < Kh; kh++)
                      for (size_t kw = 0; kw < Kw; kw++) {
                        int hi = (int)(ho * sh + kh) - (int)pad_h;
                        int wi = (int)(wo * sw + kw) - (int)pad_w;
                        if (hi < 0 || hi >= (int)Hi || wi < 0 || wi >= (int)Wi) continue;
                        if (is_dw) {
                            // DepthWise: weight[Kh,Kw,1,Cin], Cin==Cout
                            float w = weight[((kh * Kw + kw) * 1 + 0) * Cin + co];
                            float v = inp[((nb * Hi + hi) * Wi + wi) * Cin + co];
                            acc += v * w;
                        } else {
                            // Standard: weight[Kh,Kw,Cin,Cout]
                            for (size_t ci = 0; ci < Cin; ci++) {
                                float w = weight[((kh * Kw + kw) * Cin + ci) * Cout + co];
                                float v = inp[((nb * Hi + hi) * Wi + wi) * Cin + ci];
                                acc += v * w;
                            }
                        }
                      }
                    out[((nb * Ho + ho) * Wo + wo) * Cout + co] = acc;
                  }
        }
    } else {
        // 默认: 直通第一个输入
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        for (size_t i = 0; i < n; ++i) out[i] = in0 ? in0[i] : 0.0f;
    }
}

// Generic construct: creates a TypicalOp with op type info
// Source: typical_op_prepare.cc, op_registry_prepare.cc:97
// 从 OpDef (io.opdef_ptr) 提取 op_data 参数 blob 存入 op->params，
// 供后续 tiling / 指令选择 / execute 使用。
static std::unique_ptr<Op> generic_construct(const OpIoPtrs& io, op_id_t id, const char* op_name) {
    auto op = std::make_unique<TypicalOp>();
    op->graph = io.graph_prepare;
    if (op_name) op->op_type_name = op_name;
    op->op_id = id;
    if (io.opdef_ptr) {
        const OpDef* opdef = static_cast<const OpDef*>(io.opdef_ptr);
        op->params = opdef->op_data;
        op->cached_out_def = opdef->output_def;
        op->exec_inputs = opdef->inputs;
        // Populate each input connection's source OutputDef so the host
        // reference executor can infer input shapes (needed for MatMul).
        if (io.graph_prepare) {
            for (auto& conn : op->exec_inputs) {
                auto* src_od = io.graph_prepare->get_op_at(conn.src_id);
                if (src_od) conn.src_out_def = src_od->output_def;
            }
        }
        // 指令选择: 根据 op 类型 + dtype + SoC 选 wrapper
        DType dt = static_cast<DType>(opdef->output_def.dtype);
        uint32_t soc = 75;  // 默认 v75; 真实从 env 取
        op->wrapper = select_wrapper(op->op_type_name, dt, soc);
    }
    return op;
}

// All 200+ op constructors delegate to generic_construct for now
// Each would have specific parameter parsing in a full implementation

std::unique_ptr<Op> ConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthWiseConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DilatedConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GroupedConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SparseConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> IndiceConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvResidualScalingOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvFusedBiasScaleOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvActivationsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvConvertTransposeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvSpecialEncodingsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MatMulOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DenseOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AddOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SubOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MulOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DivOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MinMaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SquaredDiffOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ElementWiseFloorDivOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ElementWiseSignOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ReluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SigmoidOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TanhOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> EluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GeluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SwishOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HardSigmoidOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HardSwishOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SoftplusOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LeakyReluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PReluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ClampOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LinearClipOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ExpOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SqrtRsqrtOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PowerOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AbsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SinOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AtanOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AsinOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogitOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CeilingOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FloorOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RoundOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> NegOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AvgPoolOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MaxPoolOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BatchNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LayerNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> InstanceNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GroupNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RmsNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LrnOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SoftmaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogSoftmaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MaskedSoftmaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LstmOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GruOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ReshapeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TransposeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConcatOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SplitOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FlattenOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ChannelShuffleOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SliceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> StridedSliceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PadOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MirrorPadOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GatherOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GatherElementsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GatherNdOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ScatterElementsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ScatterNdOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ReduceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ArgMinMaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CumSumOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CastOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FpCastOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> QuantizeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DequantizeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RequantizeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CompareOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CompareEqualOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogicalOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogicalCompareOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SelectOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> IsInfOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> IsNanOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeBilinearOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeNearestOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeTrilinearOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeCubicOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TopKOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> NmsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> OneHotOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GridSampleOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RoiAlignOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ExtractGlimpseOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> EinsumOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HadamardOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SwiGluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ToRgbOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> StftOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SpaceToDepthOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthToSpaceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FrameToDepthOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthToFrameOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SpaceToBatchOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BatchToSpaceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RotaryPosEmbdOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RopeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RopeCoeffPackOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BiasAddOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HashtableLookupOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DecodeBboxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvertCenterToCornerOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RandomNormalLikeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RandomUniformLikeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BitrearrangeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> NonZeroOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AllTrueOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PartialSumOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthAccumulateOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> WidthToHeightOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> UnpackOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TileOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConditionalOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConditionalAddOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SwitchedOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }

// Op registration helper
// Source: op_package_registry.cc, op_package_ops_opts_registration.cc
// Must be called explicitly to register all ops (avoids static init ordering issues)
static bool ops_registered = false;

void register_all_ops() {
    if (ops_registered) return;
    ops_registered = true;
    auto& reg = OpRegistry::instance();
        // Conv ops
        reg.register_op_fn("Conv", ConvOp::construct);
        reg.register_op_fn("DepthWiseConv2d", DepthWiseConvOp::construct);
        reg.register_op_fn("DilatedConv", DilatedConvOp::construct);
        reg.register_op_fn("GroupedConv", GroupedConvOp::construct);
        reg.register_op_fn("SparseConv", SparseConvOp::construct);
        reg.register_op_fn("IndiceConv", IndiceConvOp::construct);
        reg.register_op_fn("ConvResidualScaling", ConvResidualScalingOp::construct);
        reg.register_op_fn("ConvFusedBiasScale", ConvFusedBiasScaleOp::construct);
        reg.register_op_fn("ConvActivations", ConvActivationsOp::construct);
        reg.register_op_fn("ConvConvertTranspose", ConvConvertTransposeOp::construct);
        reg.register_op_fn("ConvSpecialEncodings", ConvSpecialEncodingsOp::construct);
        // MatMul
        reg.register_op_fn("MatMul", MatMulOp::construct);
        reg.register_op_fn("Dense", DenseOp::construct);
        // Elementwise
        reg.register_op_fn("Add", AddOp::construct);
        reg.register_op_fn("Sub", SubOp::construct);
        reg.register_op_fn("Mul", MulOp::construct);
        reg.register_op_fn("Div", DivOp::construct);
        reg.register_op_fn("MinMax", MinMaxOp::construct);
        reg.register_op_fn("SquaredDifference", SquaredDiffOp::construct);
        reg.register_op_fn("ElementWiseFloorDiv", ElementWiseFloorDivOp::construct);
        reg.register_op_fn("ElementWiseSign", ElementWiseSignOp::construct);
        // Activations
        reg.register_op_fn("Relu", ReluOp::construct);
        reg.register_op_fn("Sigmoid", SigmoidOp::construct);
        reg.register_op_fn("Tanh", TanhOp::construct);
        reg.register_op_fn("Elu", EluOp::construct);
        reg.register_op_fn("Gelu", GeluOp::construct);
        reg.register_op_fn("Swish", SwishOp::construct);
        reg.register_op_fn("HardSigmoid", HardSigmoidOp::construct);
        reg.register_op_fn("HardSwish", HardSwishOp::construct);
        reg.register_op_fn("Softplus", SoftplusOp::construct);
        reg.register_op_fn("LeakyRelu", LeakyReluOp::construct);
        reg.register_op_fn("PRelu", PReluOp::construct);
        reg.register_op_fn("Clamp", ClampOp::construct);
        reg.register_op_fn("LinearClip", LinearClipOp::construct);
        // Math
        reg.register_op_fn("Exp", ExpOp::construct);
        reg.register_op_fn("Log", LogOp::construct);
        reg.register_op_fn("Sqrt", SqrtRsqrtOp::construct);
        reg.register_op_fn("Rsqrt", SqrtRsqrtOp::construct);
        reg.register_op_fn("Power", PowerOp::construct);
        reg.register_op_fn("Abs", AbsOp::construct);
        reg.register_op_fn("Sin", SinOp::construct);
        reg.register_op_fn("Cos", SinOp::construct);
        reg.register_op_fn("Atan", AtanOp::construct);
        reg.register_op_fn("Asin", AsinOp::construct);
        reg.register_op_fn("Logit", LogitOp::construct);
        reg.register_op_fn("Ceiling", CeilingOp::construct);
        reg.register_op_fn("Floor", FloorOp::construct);
        reg.register_op_fn("Round", RoundOp::construct);
        reg.register_op_fn("Neg", NegOp::construct);
        // Pooling
        reg.register_op_fn("AvgPool", AvgPoolOp::construct);
        reg.register_op_fn("MaxPool", MaxPoolOp::construct);
        // Normalization
        reg.register_op_fn("BatchNorm", BatchNormOp::construct);
        reg.register_op_fn("LayerNorm", LayerNormOp::construct);
        reg.register_op_fn("InstanceNorm", InstanceNormOp::construct);
        reg.register_op_fn("GroupNorm", GroupNormOp::construct);
        reg.register_op_fn("RmsNorm", RmsNormOp::construct);
        reg.register_op_fn("Lrn", LrnOp::construct);
        // Softmax
        reg.register_op_fn("Softmax", SoftmaxOp::construct);
        reg.register_op_fn("LogSoftmax", LogSoftmaxOp::construct);
        reg.register_op_fn("MaskedSoftmax", MaskedSoftmaxOp::construct);
        // RNN
        reg.register_op_fn("Lstm", LstmOp::construct);
        reg.register_op_fn("Gru", GruOp::construct);
        // Shape
        reg.register_op_fn("Reshape", ReshapeOp::construct);
        reg.register_op_fn("Transpose", TransposeOp::construct);
        reg.register_op_fn("Concat", ConcatOp::construct);
        reg.register_op_fn("Split", SplitOp::construct);
        reg.register_op_fn("Flatten", FlattenOp::construct);
        reg.register_op_fn("ChannelShuffle", ChannelShuffleOp::construct);
        // Slice/Pad
        reg.register_op_fn("Slice", SliceOp::construct);
        reg.register_op_fn("StridedSlice", StridedSliceOp::construct);
        reg.register_op_fn("Pad", PadOp::construct);
        reg.register_op_fn("MirrorPad", MirrorPadOp::construct);
        // Gather/Scatter
        reg.register_op_fn("Gather", GatherOp::construct);
        reg.register_op_fn("GatherElements", GatherElementsOp::construct);
        reg.register_op_fn("GatherNd", GatherNdOp::construct);
        reg.register_op_fn("ScatterElements", ScatterElementsOp::construct);
        reg.register_op_fn("ScatterNd", ScatterNdOp::construct);
        // Reduction
        reg.register_op_fn("Reduce", ReduceOp::construct);
        reg.register_op_fn("ArgMin", ArgMinMaxOp::construct);
        reg.register_op_fn("ArgMax", ArgMinMaxOp::construct);
        reg.register_op_fn("CumSum", CumSumOp::construct);
        // Cast/Quantize
        reg.register_op_fn("Cast", CastOp::construct);
        reg.register_op_fn("FpCast", FpCastOp::construct);
        reg.register_op_fn("Quantize", QuantizeOp::construct);
        reg.register_op_fn("Dequantize", DequantizeOp::construct);
        reg.register_op_fn("Requantize", RequantizeOp::construct);
        // Compare
        reg.register_op_fn("Compare", CompareOp::construct);
        reg.register_op_fn("CompareEqual", CompareEqualOp::construct);
        reg.register_op_fn("LogicalAnd", LogicalOp::construct);
        reg.register_op_fn("LogicalOr", LogicalOp::construct);
        reg.register_op_fn("LogicalNot", LogicalOp::construct);
        reg.register_op_fn("LogicalXor", LogicalOp::construct);
        reg.register_op_fn("LogicalCompare", LogicalCompareOp::construct);
        reg.register_op_fn("Select", SelectOp::construct);
        reg.register_op_fn("IsInf", IsInfOp::construct);
        reg.register_op_fn("IsNan", IsNanOp::construct);
        // Resize
        reg.register_op_fn("ResizeBilinear", ResizeBilinearOp::construct);
        reg.register_op_fn("ResizeNearest", ResizeNearestOp::construct);
        reg.register_op_fn("ResizeTrilinear", ResizeTrilinearOp::construct);
        reg.register_op_fn("ResizeCubic", ResizeCubicOp::construct);
        // Other
        reg.register_op_fn("TopK", TopKOp::construct);
        reg.register_op_fn("NMS", NmsOp::construct);
        reg.register_op_fn("OneHot", OneHotOp::construct);
        reg.register_op_fn("GridSample", GridSampleOp::construct);
        reg.register_op_fn("RoiAlign", RoiAlignOp::construct);
        reg.register_op_fn("ExtractGlimpse", ExtractGlimpseOp::construct);
        reg.register_op_fn("Einsum", EinsumOp::construct);
        reg.register_op_fn("Hadamard", HadamardOp::construct);
        reg.register_op_fn("SwiGlu", SwiGluOp::construct);
        reg.register_op_fn("ToRgb", ToRgbOp::construct);
        reg.register_op_fn("Stft", StftOp::construct);
        // Space/Depth
        reg.register_op_fn("SpaceToDepth", SpaceToDepthOp::construct);
        reg.register_op_fn("DepthToSpace", DepthToSpaceOp::construct);
        reg.register_op_fn("FrameToDepth", FrameToDepthOp::construct);
        reg.register_op_fn("DepthToFrame", DepthToFrameOp::construct);
        reg.register_op_fn("SpaceToBatch", SpaceToBatchOp::construct);
        reg.register_op_fn("BatchToSpace", BatchToSpaceOp::construct);
        // Attention/RoPE
        reg.register_op_fn("RotaryPosEmbd", RotaryPosEmbdOp::construct);
        reg.register_op_fn("Rope", RopeOp::construct);
        reg.register_op_fn("RopeCoeffPack", RopeCoeffPackOp::construct);
        // Misc
        reg.register_op_fn("BiasAdd", BiasAddOp::construct);
        reg.register_op_fn("HashtableLookup", HashtableLookupOp::construct);
        reg.register_op_fn("DecodeBbox", DecodeBboxOp::construct);
        reg.register_op_fn("ConvertCenterToCorner", ConvertCenterToCornerOp::construct);
        reg.register_op_fn("RandomNormalLike", RandomNormalLikeOp::construct);
        reg.register_op_fn("RandomUniformLike", RandomUniformLikeOp::construct);
        reg.register_op_fn("Bitrearrange", BitrearrangeOp::construct);
        reg.register_op_fn("NonZero", NonZeroOp::construct);
        reg.register_op_fn("AllTrue", AllTrueOp::construct);
        reg.register_op_fn("PartialSum", PartialSumOp::construct);
        reg.register_op_fn("DepthAccumulate", DepthAccumulateOp::construct);
        reg.register_op_fn("WidthToHeight", WidthToHeightOp::construct);
        reg.register_op_fn("Unpack", UnpackOp::construct);
        reg.register_op_fn("Tile", TileOp::construct);
        // Conditional/Switch
        reg.register_op_fn("Conditional", ConditionalOp::construct);
        reg.register_op_fn("ConditionalAdd", ConditionalAddOp::construct);
        reg.register_op_fn("Switched", SwitchedOp::construct);

    // HLX/HMX ops
    register_hlx_hmx_ops();
}

} // namespace hnnx
