#include "hnnx/ops/ops.hpp"
#include "hnnx/ir/scalar_params.hpp"
#include "hnnx/ir/op_registry.hpp"
#include "hnnx/ir/graph_prepare.hpp"
#include "hnnx/cost/cost_model.hpp"
#include <cmath>
#include <cstring>
#include <memory>
#include <algorithm>
#include <numeric>

namespace hnnx {

void register_hlx_hmx_ops();

// 指令选择: 根据 op 类型 + dtype + SoC 选 HVX/HMX wrapper。
// Source: hvx_wrapper_select.cc, hmx_op_select.cc
// 真实库查 op 是否在 HMX 支持表 + dtype 是否量化 + SoC 是否有 HMX 单元。
HwWrapper select_wrapper(const std::string& op_type, DType dtype, uint32_t soc_type) {
    // HMX 适合 Conv/MatMul 等密集矩阵运算 (v73+ 有 HMX)
    bool is_matrix_op = (op_type == "Conv" || op_type == "DepthWiseConv2d" ||
                         op_type == "DilatedConv" || op_type == "GroupedConv" ||
                         op_type == "MatMul" || op_type == "Dense");
    bool hmx_capable = (soc_type >= 73);  // v73+ 有 HMX
    bool quant_dtype = (dtype == DType::Int8 || dtype == DType::Int16 ||
                        dtype == DType::Int4 || dtype == DType::UInt4 ||
                        dtype == DType::FP8_E4M3 || dtype == DType::FP8_E5M2 ||
                        dtype == DType::MXFP4);
    if (is_matrix_op && hmx_capable && quant_dtype) {
        return (dtype == DType::Int4 || dtype == DType::UInt4) ? HwWrapper::HMX_MatrixInt4
                                                              : HwWrapper::HMX_Matrix;
    }
    // HVX 向量内核处理 elementwise/激活/norm 等 (所有 SoC 都有 HVX)
    if (dtype != DType::Float32 && dtype != DType::Float16 && dtype != DType::BFloat16) {
        return HwWrapper::HVX_Vector;
    }
    // 浮点路径在真实库走 HTA 或标量后备; host reimpl 用标量
    return HwWrapper::HVX_Scalar;
}

// TypicalOp::cost: use cost model to estimate
float TypicalOp::cost(const hnnx::Graph* g) const {
    // Source: typical_op_prepare.cc
    if (op_type_name.empty()) return 1.0f;
    static costbased::CostSource cs;
    static bool init = false;
    if (!init) { cs.init_for_soc("v75"); init = true; }
    return cs.get_prediction_from_cost_model(op_type_name, this, nullptr, {});
}

void TypicalOp::serialize_internal(Serializer& ser, int chkpt_type) const {
    // Source: serialize_oplist.cc, Op::serialize_internal @0x10bc690
    // [反汇编证据 libQnnHtp.so v2.48] serialize_op @0x12ec630:
    //   - 标记 0x1303EE71 硬编码 (mov r13d,0x1303ee71 @0x12ec688)
    //   - type 字段 = (extra_info[0x18] >> 6 & 0xf) << 24, 加 HMX/flags 修正
    //     0x01=compute, 0x02=memory, 0x03=sync, 0x04=DMA(DmaCheckpoint), 0x0b=HMX
    //   - block_ref = extra_info[0x24] & 0xFFFFFF | (0x03<<24)
    //   - SET/WAIT (make_dma_checkpoint_op @0xd958d0) 共享 serialize_internal @0xd969a0
    //     → 字节不可区分; 详见 reference/docs/schedule_analysis.md
    // In the real binary each Op writes its own record here. In this
    // reimplementation the runlist writer (GraphPrepare::serialize_opdef, driven
    // by do_serialize) emits one TAG_OP_RECORD per op from the OpDef, which
    // carries the full graph structure; the execution Op is regenerated by the
    // op factory at load time. This hook is therefore a no-op: the serializer
    // is driven by the graph, not by individual Op instances.
    (void)ser; (void)chkpt_type;
}

// TypicalOp::execute (3-arg): delegate to 4-arg with empty in_defs
void TypicalOp::execute(const std::vector<const uint8_t*>& inputs,
                        uint8_t* output,
                        const OutputDef& out_def) const {
    execute(inputs, output, out_def, {});
}

// TypicalOp::execute (4-arg, with input OutputDefs): host-side reference 实现 (D 阶段)。
// 按 op_type_name 分派到对应的数值内核。inputs/outputs 是扁平字节缓冲，
// 假设 Float32 布局 (真实库按 dtype/wrapper 选量化内核，这里用浮点参考)。
// output_def.dims 描述输出形状; 元素数 = dims 乘积。
// in_defs 提供各输入的 OutputDef, 供 MatMul 等需要输入形状的 op 使用。
// 这是 correctness reference, 非性能路径。
void TypicalOp::execute(const std::vector<const uint8_t*>& inputs,
                        uint8_t* output,
                        const OutputDef& out_def,
                        const std::vector<OutputDef>& in_defs) const {
    if (!output) return;
    float* out = reinterpret_cast<float*>(output);
    // 输出元素数
    size_t n = 1;
    for (uint32_t i = 0; i < out_def.rank && i < 5; ++i)
        n *= static_cast<size_t>(out_def.dims[i]);
    if (n == 0) n = 1;

    const auto in_float = [&](size_t idx, size_t i) -> float {
        if (idx >= inputs.size() || !inputs[idx]) return 0.0f;
        return reinterpret_cast<const float*>(inputs[idx])[i];
    };
    /* numpy 广播: 右对齐逐轴(probe rope Mul 的第二操作数 [1,32,1,16]
     * 中间轴广播 —— 线性 i%n 展开是错的) */
    const auto in_bc = [&](size_t idx, size_t i) -> float {
        if (idx >= inputs.size() || !inputs[idx]) return 0.0f;
        /* numpy 广播: 全 rank 右对齐(不去尾 1 —— 输入末维 1 广播到输出
         * 大维时, 去尾会把它吃掉造成 64 vs 128 假冲突, oid 1231 实锤) */
        uint32_t ork = out_def.rank;
        if (ork > 8) ork = 8;
        uint32_t ir = (idx < in_defs.size()) ? in_defs[idx].rank : 0;
        if (ir > 8) ir = 8;
        uint32_t lead = (ork > ir) ? (ork - ir) : 0;
        uint32_t off = (ir > ork) ? (ir - ork) : 0;
        uint32_t istr[8] = {1, 1, 1, 1, 1, 1, 1, 1}, ostr[8] = {1, 1, 1, 1, 1, 1, 1, 1};
        for (int d = (int)ir - 2; d >= 0; d--)
            istr[d] = istr[d + 1] * in_defs[idx].dims[off + d + 1];
        for (int d = (int)ork - 2; d >= 0; d--) ostr[d] = ostr[d + 1] * out_def.dims[d + 1];
        uint32_t rem = (uint32_t)i, in_lin = 0;
        for (uint32_t d = 0; d < ork; d++) {
            uint32_t c = rem / ostr[d];
            rem %= ostr[d];
            if (d < lead) continue;
            uint32_t idim = in_defs[idx].dims[off + (d - lead)];
            if (idim > 1) in_lin += c * istr[d - lead];
        }
        return reinterpret_cast<const float*>(inputs[idx])[in_lin];
    };

    if (op_type_name == "Relu" || op_type_name == "ConvActivations") {
        // Relu: max(0, x); ConvActivations (post-fusion): 同 Relu 语义对第一个输入
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        for (size_t i = 0; i < n; ++i) out[i] = in0 ? std::max(0.0f, in0[i]) : 0.0f;
    } else if (op_type_name == "Add" || op_type_name == "ElementWiseBinary") {
        for (size_t i = 0; i < n; ++i) out[i] = in_bc(0, i) + in_bc(1, i);
    } else if (op_type_name == "Eltwise_Binary") {
        /* QNN 2.48 枚举: ADD=0 AND=1 DIVIDE=2 ... MULTIPLY=13 ...
         * SUBTRACT=18 POWER=16(与旧版 0/1/2/3=ADD/SUB/MUL/DIV 不同 —
         * probe rope Mul(13)/Div(2) 实锤) */
        auto spb = unpack_scalar_params(params);
        int oper = 0;
        if (const ScalarParam* p = scalar_get(spb, "operation"))
            oper = (int)(p->is_numeric ? p->value_num
                                       : std::strtol(p->value_str.c_str(), nullptr, 10));
        if (oper == 13) {
            for (size_t i = 0; i < n; ++i) out[i] = in_bc(0, i) * in_bc(1, i);
        } else if (oper == 2) {
            for (size_t i = 0; i < n; ++i) {
                float d = in_bc(1, i);
                out[i] = (d != 0.0f) ? in_bc(0, i) / d : 0.0f;
            }
        } else if (oper == 18) {
            for (size_t i = 0; i < n; ++i) out[i] = in_bc(0, i) - in_bc(1, i);
        } else if (oper == 16) {
            for (size_t i = 0; i < n; ++i) out[i] = std::pow(in_bc(0, i), in_bc(1, i));
        } else {
            for (size_t i = 0; i < n; ++i) out[i] = in_bc(0, i) + in_bc(1, i);
        }
    } else if (op_type_name == "Sub") {
        for (size_t i = 0; i < n; ++i) out[i] = in_bc(0, i) - in_bc(1, i);
    } else if (op_type_name == "Mul") {
        for (size_t i = 0; i < n; ++i) out[i] = in_bc(0, i) * in_bc(1, i);
    } else if (op_type_name == "Div") {
        for (size_t i = 0; i < n; ++i) {
            float d = in_bc(1, i);
            out[i] = (d != 0.0f) ? in_bc(0, i) / d : 0.0f;
        }
    } else if (op_type_name == "Sigmoid") {
        for (size_t i = 0; i < n; ++i) out[i] = 1.0f / (1.0f + std::exp(-in_float(0, i)));
    } else if (op_type_name == "Tanh") {
        for (size_t i = 0; i < n; ++i) out[i] = std::tanh(in_float(0, i));
    } else if (op_type_name == "Exp") {
        for (size_t i = 0; i < n; ++i) out[i] = std::exp(in_float(0, i));
    } else if (op_type_name == "Neg") {
        for (size_t i = 0; i < n; ++i) out[i] = -in_float(0, i);

    } else if (op_type_name == "Eltwise_Unary" || op_type_name == "ElementWiseNeuron") {
        /* QNN 2.48 枚举(数字, 非字符串):
         * Unary: ABS=0 ... COS=4 EXP=5 FLOOR=6 LOG=7 NEG=8 RECIPROCAL=10
         *        RSQRT=12 SIN=14 SQRT=15
         * Neuron: GELU=1 HARD_SWISH=3 RELU=4 SIGMOID=6 SOFTPLUS=7 TANH=8
         * 两族枚举值域重叠 → 按 op 类型分派, 不得共享 switch(GDN softplus
         * 负输入实锤: 共享时 case 7 命中 Unary LOG → 负值输出 0) */
        auto sp = unpack_scalar_params(params);
        const ScalarParam* po = scalar_get(sp, "operation");
        int oper = -1;
        if (po)
            oper = (int)(po->is_numeric ? po->value_num
                                        : std::strtol(po->value_str.c_str(), nullptr, 10));
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (op_type_name == "ElementWiseNeuron") {
            for (size_t i = 0; i < n; ++i) {
                float x = in0 ? in0[i] : 0.0f;
                switch (oper) {
                case 1:  out[i] = 0.5f * x * (1.0f + std::tanh(0.7978845608f *
                            (x + 0.044715f * x * x * x))); break;          /* GELU */
                case 3: { /* HARD_SWISH: x·relu6(x+3)/6 */
                    float v = x + 3.0f;
                    if (v < 0.0f) v = 0.0f;
                    if (v > 6.0f) v = 6.0f;
                    out[i] = x * v / 6.0f; break;
                }
                case 4:  out[i] = std::max(0.0f, x); break;               /* RELU */
                case 6:  out[i] = 1.0f / (1.0f + std::exp(-x)); break;     /* SIGMOID */
                case 7: { /* SOFTPLUS: 稳定化 log(1+e^x)(x 大时 exp 溢出) */
                    if (x > 30.0f) out[i] = x;
                    else if (x < -30.0f) out[i] = std::exp(x);
                    else out[i] = std::log1pf(std::exp(x));
                    break;
                }
                case 8:  out[i] = std::tanh(x); break;                     /* TANH */
                default: out[i] = x; break;
                }
            }
        } else {
        for (size_t i = 0; i < n; ++i) {
            float x = in0 ? in0[i] : 0.0f;
            switch (oper) {
            case 8:  out[i] = -x; break;                                   /* NEG */
            case 5:  out[i] = std::exp(x); break;                          /* EXP */
            case 15: out[i] = (x >= 0) ? std::sqrt(x) : 0.0f; break;       /* SQRT */
            case 12: out[i] = (x > 0) ? 1.0f / std::sqrt(x) : 0.0f; break; /* RSQRT */
            case 7:  out[i] = (x > 0) ? std::log(x) : 0.0f; break;         /* LOG */
            case 6:  out[i] = std::floor(x); break;                        /* FLOOR */
            case 0:  out[i] = std::fabs(x); break;                         /* ABS */
            case 14: out[i] = std::sin(x); break;                          /* SIN */
            case 4:  out[i] = std::cos(x); break;                          /* COS */
            case 10: out[i] = (x != 0.0f) ? 1.0f / x : 0.0f; break;        /* RECIPROCAL */
            default: out[i] = x; break;
            }
        }
        }
    } else if (op_type_name == "Eltwise_Ternary") {
        // SELECT 语义(eltwise_type scalar): out = in0(cond) ? in1 : in2
        // (GDN chunk 的 masked_fill → Where 展开)
        auto sp = unpack_scalar_params(params);
        const ScalarParam* pt = scalar_get(sp, "eltwise_type");
        std::string t = pt ? pt->value_str : "";
        /* ElementWiseSelect(Where): 三输入 numpy 广播
         * (GDN Trilu 链: cond [64,64] + 标量 zero + 5D 数据) */
        if (getenv("GEHTP_EXDIAG")) {
            std::fprintf(stderr, "[terdiag] n=%zu outr=%u in_defs=%zu",
                         n, out_def.rank, in_defs.size());
            for (size_t k = 0; k < in_defs.size(); k++)
                std::fprintf(stderr, " [r%u:%u,%u,%u,%u,%u]",
                             in_defs[k].rank, in_defs[k].dims[0],
                             in_defs[k].dims[1], in_defs[k].dims[2],
                             in_defs[k].dims[3], in_defs[k].dims[4]);
            std::fprintf(stderr, "\n");
        }
        for (size_t i = 0; i < n; ++i) {
            float cv = in_bc(0, i);
            out[i] = (cv != 0.0f) ? in_bc(1, i) : in_bc(2, i);
        }
    } else if (op_type_name == "CumSum" || op_type_name == "CumulativeSum") {
        // axis 由 scalar_params 决定; 输入形状取 in_defs[0](缺省 = out_def)
        auto sp = unpack_scalar_params(params);
        const ScalarParam* pa = scalar_get(sp, "axis");
        int64_t axis = pa ? pa->as_int() : 0;
        std::vector<size_t> dims;
        const OutputDef* in_od = in_defs.empty() ? &out_def : &in_defs[0];
        for (uint32_t i = 0; i < in_od->rank && i < 5; ++i) dims.push_back(in_od->dims[i]);
        if (dims.empty()) dims.push_back(n);
        if (axis < 0) axis += static_cast<int64_t>(dims.size());
        size_t ax = static_cast<size_t>(std::max<int64_t>(axis, 0));
        size_t outer = 1, inner = 1, axlen = 1;
        for (size_t d = 0; d < dims.size(); ++d) {
            if (d < ax) outer *= dims[d];
            else if (d == ax) axlen = dims[d];
            else inner *= dims[d];
        }
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        for (size_t o = 0; o < outer; ++o)
            for (size_t k = 0; k < inner; ++k) {
                float acc = 0.0f;
                for (size_t a = 0; a < axlen; ++a) {
                    acc += in0 ? in0[(o * axlen + a) * inner + k] : 0.0f;
                    out[(o * axlen + a) * inner + k] = acc;
                }
            }

    // ── Math ops (elementwise, single/dual input) ──
    } else if (op_type_name == "Power") {
        for (size_t i = 0; i < n; ++i) out[i] = std::pow(in_float(0, i), in_float(1, i));
    } else if (op_type_name == "Log") {
        for (size_t i = 0; i < n; ++i) { float v = in_float(0, i); out[i] = (v > 0) ? std::log(v) : 0.0f; }
    } else if (op_type_name == "Sqrt") {
        for (size_t i = 0; i < n; ++i) { float v = in_float(0, i); out[i] = (v >= 0) ? std::sqrt(v) : 0.0f; }
    } else if (op_type_name == "Rsqrt") {
        for (size_t i = 0; i < n; ++i) { float v = in_float(0, i); out[i] = (v > 0) ? 1.0f/std::sqrt(v) : 0.0f; }
    } else if (op_type_name == "Abs") {
        for (size_t i = 0; i < n; ++i) out[i] = std::fabs(in_float(0, i));
    } else if (op_type_name == "Ceiling") {
        for (size_t i = 0; i < n; ++i) out[i] = std::ceil(in_float(0, i));
    } else if (op_type_name == "Floor") {
        for (size_t i = 0; i < n; ++i) out[i] = std::floor(in_float(0, i));
    } else if (op_type_name == "Round") {
        for (size_t i = 0; i < n; ++i) out[i] = std::round(in_float(0, i));
    } else if (op_type_name == "Sin") {
        for (size_t i = 0; i < n; ++i) out[i] = std::sin(in_float(0, i));
    } else if (op_type_name == "Cos") {
        for (size_t i = 0; i < n; ++i) out[i] = std::cos(in_float(0, i));
    } else if (op_type_name == "SquaredDifference") {
        for (size_t i = 0; i < n; ++i) { float d = in_float(0,i) - in_float(1,i); out[i] = d*d; }

    // ── Activation ops ──
    } else if (op_type_name == "Gelu") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = 0.5f * x * (1.0f + std::erf(x * 0.7071067811865475f));
        }
    } else if (op_type_name == "LeakyRelu") {
        float alpha = 0.01f;
        if (params.size() >= 4) std::memcpy(&alpha, params.data(), 4);
        for (size_t i = 0; i < n; ++i) { float x = in_float(0,i); out[i] = x >= 0 ? x : alpha*x; }
    } else if (op_type_name == "Elu") {
        float alpha = 1.0f;
        if (params.size() >= 4) std::memcpy(&alpha, params.data(), 4);
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = x >= 0 ? x : alpha * (std::exp(x) - 1.0f);
        }
    } else if (op_type_name == "Swish") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = x / (1.0f + std::exp(-x));
        }
    } else if (op_type_name == "HardSigmoid") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = std::max(0.0f, std::min(1.0f, x * 0.2f + 0.5f));
        }
    } else if (op_type_name == "HardSwish") {
        for (size_t i = 0; i < n; ++i) {
            float x = in_float(0, i);
            out[i] = x * std::max(0.0f, std::min(1.0f, x * 0.2f + 0.5f));
        }
    } else if (op_type_name == "Softplus") {
        for (size_t i = 0; i < n; ++i) out[i] = std::log(1.0f + std::exp(in_float(0, i)));
    } else if (op_type_name == "Clamp") {
        float lo = -1e30f, hi = 1e30f;
        if (params.size() >= 8) { std::memcpy(&lo, params.data(), 4); std::memcpy(&hi, params.data()+4, 4); }
        for (size_t i = 0; i < n; ++i) out[i] = std::max(lo, std::min(hi, in_float(0, i)));
    } else if (op_type_name == "MinMax") {
        // MinMax: element-wise min of two inputs
        for (size_t i = 0; i < n; ++i) out[i] = std::min(in_float(0,i), in_float(1,i));

    // ── Shape ops ──
    } else if (op_type_name == "Reshape" || op_type_name == "Flatten") {
        // Data layout unchanged; just copy elements
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (in0) { std::memcpy(out, in0, n * sizeof(float)); }
        else { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; }
    } else if (op_type_name == "Transpose") {
        // Transpose: permute dimensions.  inputs[0]=data, inputs[1]=perm (int32)
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; }
        else {
            uint32_t rank = out_def.rank;
            std::vector<uint32_t> out_dims(rank), perm(rank);
            for (uint32_t d = 0; d < rank; d++) out_dims[d] = out_def.dims[d];
            // Read perm from second input or from params
            // perm 长度可能与 rank 不同(QNN 前导 1 填充): 前导维恒等, 尾部按 perm 平移
            uint32_t p_elems = rank;
            if (inputs.size() > 1 && inputs[1] && in_defs.size() > 1) {
                p_elems = 1;
                for (uint32_t d = 0; d < in_defs[1].rank && d < 5; ++d)
                    p_elems *= in_defs[1].dims[d];
                if (p_elems == 0 || p_elems > rank) p_elems = rank;
            }
            for (uint32_t d = 0; d < rank; d++) perm[d] = d;
            if (inputs.size() > 1 && inputs[1]) {
                const int32_t* p = reinterpret_cast<const int32_t*>(inputs[1]);
                uint32_t off = rank - p_elems;
                for (uint32_t d = 0; d < p_elems; d++)
                    perm[off + d] = static_cast<uint32_t>(p[d]) + off;
            } else {
                for (uint32_t d = 0; d < rank; d++) perm[d] = rank - 1 - d;
            }
            // Compute input shape from in_defs or infer from output + perm
            // (右对齐: 输入 rank 小于输出 rank 时前导 1 填充)
            std::vector<uint32_t> in_dims(rank, 1);
            if (!in_defs.empty()) {
                uint32_t ir = in_defs[0].rank;
                uint32_t off = rank > ir ? rank - ir : 0;
                for (uint32_t d = 0; d < ir && off + d < rank; d++)
                    in_dims[off + d] = in_defs[0].dims[d];
            } else {
                for (uint32_t d = 0; d < rank; d++) in_dims[d] = out_dims[perm[d]];
            }
            // Strides for input linear indexing
            std::vector<size_t> in_strides(rank, 1);
            for (int d = (int)rank - 2; d >= 0; d--)
                in_strides[d] = in_strides[d+1] * in_dims[d+1];
            for (size_t i = 0; i < n; ++i) {
                size_t rem = i;
                size_t src = 0;
                for (uint32_t d = 0; d < rank; d++) {
                    size_t coord = rem / (d+1 < rank ? [&]{ size_t s=1; for(uint32_t k=d+1;k<rank;k++) s*=out_dims[k]; return s; }() : 1);
                    rem %= (d+1 < rank ? [&]{ size_t s=1; for(uint32_t k=d+1;k<rank;k++) s*=out_dims[k]; return s; }() : 1);
                    src += coord * in_strides[perm[d]];
                }
                out[i] = (src < n) ? in0[src] : 0.0f;
            }
        }
    } else if (op_type_name == "StridedSlice") {
        // 4D C 序切片: ranges = [begin,end,stride]×rank(int32 经 float 缓冲
        // 传递), 由 execute_host 注入的 tensor_param 提供(inputs[1])。
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        /* ranges 是 int32 数据(execute_host 缓冲按 float 存字节, 位模式不变) */
        const int32_t* rg = (inputs.size() > 1) ? reinterpret_cast<const int32_t*>(inputs[1]) : nullptr;
        if (!in0 || !rg) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; }
        else {
            uint32_t rank = out_def.rank;
            if (rank > 4) rank = 4;
            /* ranges 轴数 = param 元素数/3; 与 rank 不同时右对齐(前导轴恒等,
             * QNN 前导 1 填充) */
            uint32_t n_axes = rank;
            if (in_defs.size() > 1) {
                size_t en = 1;
                for (uint32_t d = 0; d < in_defs[1].rank && d < 5; ++d)
                    en *= in_defs[1].dims[d];
                if (en % 3 == 0 && en / 3 <= rank) n_axes = (uint32_t)(en / 3);
            }
            uint32_t ax_off = rank - n_axes;
            int b[4] = {0, 0, 0, 0}, e[4] = {0, 0, 0, 0}, s[4] = {1, 1, 1, 1};
            for (uint32_t ax = 0; ax < n_axes; ax++) {
                b[ax_off + ax] = (int)rg[ax * 3 + 0];
                e[ax_off + ax] = (int)rg[ax * 3 + 1];
                s[ax_off + ax] = (int)rg[ax * 3 + 2];
                if (s[ax_off + ax] == 0) s[ax_off + ax] = 1;
            }
            /* 输入形状(in_defs[0])右对齐, 前导 1 填充 */
            uint32_t id_[4] = {1, 1, 1, 1};
            if (!in_defs.empty()) {
                uint32_t ir = in_defs[0].rank;
                uint32_t off = rank > ir ? rank - ir : 0;
                for (uint32_t ax = 0; ax < ir && off + ax < 4; ax++)
                    id_[off + ax] = in_defs[0].dims[ax];
            }
            size_t in_strides[4] = {1, 1, 1, 1};
            for (int d = 2; d >= 0; d--) in_strides[d] = in_strides[d + 1] * id_[d + 1];
            uint32_t od[4] = {1, 1, 1, 1};
            for (uint32_t ax = 0; ax < rank; ax++) od[ax] = out_def.dims[ax];
            size_t out_strides[4] = {1, 1, 1, 1};
            for (int d = 2; d >= 0; d--) out_strides[d] = out_strides[d + 1] * od[d + 1];
            for (size_t i = 0; i < n; i++) {
                size_t rem = i, src = 0;
                for (uint32_t d = 0; d < rank; d++) {
                    size_t c = rem / out_strides[d];
                    rem %= out_strides[d];
                    src += (size_t)(b[d] + (int)c * s[d]) * in_strides[d];
                }
                out[i] = in0[src];
            }
        }
    } else if (op_type_name == "Pad") {
        // QNN Pad: scalar scheme(0=CONSTANT 1=REFLECT 2=SYMMETRIC 3=EDGE)
        // + pad_constant_value; tensor_param pad_amount [n_axes,2] begin/end
        // (内联 data, int32 经 float 缓冲传字节)。GDN 用例: 轴 1 前 pad 32(chunk)。
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        const int32_t* pads = (inputs.size() > 1) ? reinterpret_cast<const int32_t*>(inputs[1]) : nullptr;
        float pad_val = 0.0f;
        int scheme = 0;
        auto sp2 = unpack_scalar_params(params);
        if (const ScalarParam* p = scalar_get(sp2, "pad_constant_value"))
            pad_val = (float)(p->is_numeric ? p->value_num
                                            : std::strtod(p->value_str.c_str(), nullptr));
        if (const ScalarParam* p = scalar_get(sp2, "scheme"))
            scheme = (int)(p->is_numeric ? p->value_num
                                         : std::strtol(p->value_str.c_str(), nullptr, 10));
        if (scheme != 0) {
            // 非 CONSTANT scheme 暂直通兜底(数值门兜底)
            for (size_t i = 0; i < n; ++i) out[i] = in0 ? in0[i] : 0.0f;
        } else if (!in0 || !pads) {
            for (size_t i = 0; i < n; ++i) out[i] = pad_val;
        } else {
            if (getenv("GEHTP_EXDIAG")) {
                std::fprintf(stderr, "[paddiag] n=%zu in_defs=%zu",
                             n, in_defs.size());
                for (size_t k = 0; k < in_defs.size(); k++)
                    std::fprintf(stderr, " [r%u:%u,%u,%u,%u]",
                                 in_defs[k].rank, in_defs[k].dims[0],
                                 in_defs[k].dims[1], in_defs[k].dims[2],
                                 in_defs[k].dims[3]);
                std::fprintf(stderr, " outrank=%u\n", out_def.rank);
            }
            uint32_t rank = out_def.rank;
            if (rank > 4) rank = 4;
            uint32_t od[4] = {1, 1, 1, 1};
            for (uint32_t ax = 0; ax < rank; ax++) od[ax] = out_def.dims[ax];
            /* 输入形状右对齐(前导 1 填充) */
            uint32_t id_[4] = {1, 1, 1, 1};
            if (!in_defs.empty()) {
                uint32_t ir = in_defs[0].rank;
                uint32_t off = rank > ir ? rank - ir : 0;
                for (uint32_t ax = 0; ax < ir && off + ax < 4; ax++)
                    id_[off + ax] = in_defs[0].dims[ax];
            }
            /* pads 轴数 = param 元素数/2, 右对齐 */
            uint32_t n_axes = rank;
            if (in_defs.size() > 1) {
                size_t en = 1;
                for (uint32_t d = 0; d < in_defs[1].rank && d < 5; ++d)
                    en *= in_defs[1].dims[d];
                if (en % 2 == 0 && en / 2 <= rank) n_axes = (uint32_t)(en / 2);
            }
            uint32_t ax_off = rank - n_axes;
            size_t in_strides[4] = {1, 1, 1, 1};
            for (int d = 2; d >= 0; d--) in_strides[d] = in_strides[d + 1] * id_[d + 1];
            size_t out_strides[4] = {1, 1, 1, 1};
            for (int d = 2; d >= 0; d--) out_strides[d] = out_strides[d + 1] * od[d + 1];
            for (size_t i = 0; i < n; i++) {
                size_t rem = i, src = 0;
                bool valid = true;
                for (uint32_t d = 0; d < rank; d++) {
                    size_t c = rem / out_strides[d];
                    rem %= out_strides[d];
                    /* pads 按有效轴序(before0,after0,…); 前导填充轴无 pad */
                    int64_t pbeg = (d >= ax_off) ? pads[(d - ax_off) * 2 + 0] : 0;
                    int64_t ic = (int64_t)c - pbeg;
                    if (ic < 0 || ic >= (int64_t)id_[d]) { valid = false; break; }
                    src += (size_t)ic * in_strides[d];
                }
                out[i] = valid ? in0[src] : pad_val;
            }
        }
    } else if (op_type_name == "Concat") {
        // Concat: join inputs along axis.  axis from scalar 通道
        // (params 是 pack_scalar_params blob, 开头非 axis — memcpy 直读是
        // 布局硬假设, probe 实锤越界)。
        int axis = -1;
        auto sp2 = unpack_scalar_params(params);
        if (const ScalarParam* p = scalar_get(sp2, "axis"))
            axis = (int)(p->is_numeric ? p->value_num
                                     : std::strtol(p->value_str.c_str(), nullptr, 10));
        uint32_t rank = out_def.rank;
        if (axis < 0) axis += rank;
        if (axis < 0) axis = (int)rank - 1;
        // Outer = product of dims before axis, inner = product after axis
        size_t outer = 1, inner = 1;
        for (int d = 0; d < axis; d++) outer *= out_def.dims[d];
        for (uint32_t d = (uint32_t)axis + 1; d < rank; d++) inner *= out_def.dims[d];
        size_t out_axis = out_def.dims[axis];
        size_t off = 0;
        for (size_t idx = 0; idx < inputs.size(); idx++) {
            if (!inputs[idx]) continue;
            size_t in_axis_len = 0;
            if (idx < in_defs.size() && in_defs[idx].rank > (uint32_t)axis)
                in_axis_len = in_defs[idx].dims[axis];
            else in_axis_len = out_axis / std::max<size_t>(1, inputs.size());
            const float* src = reinterpret_cast<const float*>(inputs[idx]);
            for (size_t o = 0; o < outer; o++) {
                for (size_t a = 0; a < in_axis_len; a++) {
                    for (size_t j = 0; j < inner; j++) {
                        out[o * out_axis * inner + (off + a) * inner + j] =
                            src[o * in_axis_len * inner + a * inner + j];
                    }
                }
            }
            off += in_axis_len;
        }

    // ── Pooling ──
    } else if (op_type_name == "AvgPool" || op_type_name == "MaxPool") {
        // NHWC: input [N,H,W,C], output [N,Ho,Wo,C]
        // Infer pool/stride from shapes; assume pad=0
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; }
        else {
            size_t N_b = (out_def.rank >= 4) ? out_def.dims[0] : 1;
            size_t Ho = (out_def.rank >= 4) ? out_def.dims[1] : 1;
            size_t Wo = (out_def.rank >= 4) ? out_def.dims[2] : 1;
            size_t C  = (out_def.rank >= 4) ? out_def.dims[3] : out_def.dims[out_def.rank-1];
            size_t Hi = (!in_defs.empty() && in_defs[0].rank >= 4) ? in_defs[0].dims[1] : Ho;
            size_t Wi = (!in_defs.empty() && in_defs[0].rank >= 4) ? in_defs[0].dims[2] : Wo;
            size_t sh = (Ho > 1) ? (Hi - 1) / Ho + 1 : 1;
            size_t sw = (Wo > 1) ? (Wi - 1) / Wo + 1 : 1;
            size_t kh = Hi - (Ho - 1) * sh;
            size_t kw = Wi - (Wo - 1) * sw;
            if (kh == 0) kh = 1;
            if (kw == 0) kw = 1;
            bool is_max = (op_type_name == "MaxPool");
            for (size_t nb = 0; nb < N_b; nb++)
              for (size_t ho = 0; ho < Ho; ho++)
                for (size_t wo = 0; wo < Wo; wo++)
                  for (size_t c = 0; c < C; c++) {
                    float val = is_max ? -1e30f : 0.0f;
                    size_t cnt = 0;
                    for (size_t kh_ = 0; kh_ < kh; kh_++)
                      for (size_t kw_ = 0; kw_ < kw; kw_++) {
                        size_t hi = ho*sh + kh_, wi = wo*sw + kw_;
                        if (hi < Hi && wi < Wi) {
                            float v = in0[((nb*Hi + hi)*Wi + wi)*C + c];
                            val = is_max ? std::max(val, v) : val + v;
                            cnt++;
                        }
                      }
                    if (!is_max && cnt > 0) val /= cnt;
                    out[((nb*Ho + ho)*Wo + wo)*C + c] = val;
                  }
        }

    // ── Normalization ──
    } else if (op_type_name == "RmsNorm") {
        // RMSNorm(与 LayerNorm 不同: 不减均值): y = x/sqrt(mean(x²)+eps) * γ (+β)
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        const float* scale = (inputs.size() > 1) ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        const float* bias  = (inputs.size() > 2) ? reinterpret_cast<const float*>(inputs[2]) : nullptr;
        if (!in0) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; }
        else {
            uint32_t rk = out_def.rank;
            while (rk > 0 && out_def.dims[rk - 1] == 1) rk--;
            size_t C = (rk >= 1) ? out_def.dims[rk - 1] : 1;
            if (C == 0) C = 1;
            size_t groups = n / C;
            if (groups == 0) groups = 1;
            for (size_t g = 0; g < groups; g++) {
                double acc = 0.0;
                for (size_t c = 0; c < C; c++) {
                    float v = in0[g * C + c];
                    acc += (double)v * (double)v;
                }
                float inv = 1.0f / std::sqrt((float)(acc / (double)C) + 1e-6f);
                for (size_t c = 0; c < C; c++) {
                    float v = in0[g * C + c] * inv;
                    if (scale) v *= scale[c % C];
                    if (bias) v += bias[c % C];
                    out[g * C + c] = v;
                }
            }
        }
    } else if (op_type_name == "BatchNorm" || op_type_name == "LayerNorm" ||
               op_type_name == "InstanceNorm" ||
               op_type_name == "GroupNorm") {
        // Generic normalization: inputs[0]=data, inputs[1]=scale, inputs[2]=bias
        // For host reference: normalize to zero-mean/unit-variance, then scale+bias
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        const float* scale = (inputs.size() > 1) ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        const float* bias  = (inputs.size() > 2) ? reinterpret_cast<const float*>(inputs[2]) : nullptr;
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; }
        else {
            // Determine group size: last dim for per-channel norm
            size_t C = (out_def.rank >= 1) ? out_def.dims[out_def.rank - 1] : 1;
            size_t groups = n / C;
            if (groups == 0) groups = 1;
            for (size_t g = 0; g < groups; g++) {
                float mean = 0;
                for (size_t c = 0; c < C; c++) mean += in0[g*C + c];
                mean /= C;
                float var = 0;
                for (size_t c = 0; c < C; c++) { float d = in0[g*C+c] - mean; var += d*d; }
                var /= C;
                float inv = 1.0f / std::sqrt(var + 1e-5f);
                for (size_t c = 0; c < C; c++) {
                    float v = (in0[g*C+c] - mean) * inv;
                    if (scale) v *= scale[c % C];
                    if (bias) v += bias[c % C];
                    out[g*C + c] = v;
                }
            }
        }
    } else if (op_type_name == "Gather") {
        // Gather 通用: axis(scalar, 缺省 0); indices = inputs[1](int32 经
        // float 缓冲传递); 输出 = 输入把 axis 维替换为 indices 元素数。
        // 覆盖 embedding(axis=0, idx [1,seq])与标量轴索引(axis=2 恒等面)。
        const float* tbl = inputs.size() > 0 ? reinterpret_cast<const float*>(inputs[0]) : nullptr;
        const int32_t* idx = inputs.size() > 1 ? reinterpret_cast<const int32_t*>(inputs[1]) : nullptr;
        if (!tbl || !idx) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; }
        else {
            uint32_t orank = out_def.rank;
            if (orank > 5) orank = 5;
            uint32_t irank = (!in_defs.empty()) ? in_defs[0].rank : orank;
            if (irank > 5) irank = 5;
            int axis = 0;
            auto sp2 = unpack_scalar_params(params);
            if (const ScalarParam* p = scalar_get(sp2, "axis"))
                axis = (int)(p->is_numeric ? p->value_num
                                           : std::strtol(p->value_str.c_str(), nullptr, 10));
            if (axis < 0) axis += (int)irank;
            if (axis < 0 || axis >= (int)irank) axis = 0;
            uint32_t od[5] = {1, 1, 1, 1, 1};
            for (uint32_t ax = 0; ax < orank; ax++) od[ax] = out_def.dims[ax];
            /* 输入形状: 输入 rank 可能大于输出 rank(axis 被 gather 掉) */
            uint32_t id_[5] = {1, 1, 1, 1, 1};
            if (!in_defs.empty())
                for (uint32_t ax = 0; ax < irank; ax++) id_[ax] = in_defs[0].dims[ax];
            size_t in_strides[5] = {1, 1, 1, 1, 1};
            for (int d = 3; d >= 0; d--) in_strides[d] = in_strides[d + 1] * id_[d + 1];
            size_t out_strides[5] = {1, 1, 1, 1, 1};
            for (int d = 3; d >= 0; d--) out_strides[d] = out_strides[d + 1] * od[d + 1];
            size_t m = 1;
            if (in_defs.size() > 1) {
                for (uint32_t d = 0; d < in_defs[1].rank && d < 5; ++d)
                    m *= in_defs[1].dims[d];
            }
            if (m == 0) m = 1;
            int r0 = (int)idx[0];  /* 标量 indices(GDN 用); m>1 时逐元素取 */
            if (r0 < 0) r0 += (int)id_[axis];
            bool bad0 = (r0 < 0 || r0 >= (int)id_[axis]);
            /* 输出轴 d → 输入轴: d < axis → d; d ≥ axis → d + (irank-orank)
             * (G144: 5D→4D 轴 3 被 gather 掉 shift=1; G147: rank 不变
             * 轴 2 大小 1 被 idx 替换 shift=0) */
            uint32_t shift = irank - orank;
            for (size_t i = 0; i < n; i++) {
                size_t rem = i, src = 0;
                bool bad = bad0;
                for (uint32_t d = 0; d < orank && !bad; d++) {
                    size_t c = rem / out_strides[d];
                    rem %= out_strides[d];
                    uint32_t i_ax = ((int)d >= (int)axis) ? d + shift : d;
                    if (i_ax >= irank) { bad = true; break; }
                    src += c * in_strides[i_ax];
                }
                if (!bad) src += (size_t)r0 * in_strides[axis];
                out[i] = bad ? 0.0f : tbl[src];
            }
        }
    } else if (op_type_name == "Reduce") {
        /* QNN Reduce: reduce_type 字符串(ReduceSum/Mean/Max/Min/Prod),
         * axes = tensor_param(int32), keep_dims scalar。GDN l2norm 用
         * ReduceSum(axis=末维)。 */
        auto sp = unpack_scalar_params(params);
        const ScalarParam* prt = scalar_get(sp, "reduce_type");
        std::string rt = prt ? prt->value_str : "ReduceSum";
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        const int32_t* axes = (inputs.size() > 1) ? reinterpret_cast<const int32_t*>(inputs[1]) : nullptr;
        if (!in0) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; return; }
        uint32_t irank = (!in_defs.empty()) ? in_defs[0].rank : out_def.rank;
        if (irank > 5) irank = 5;
        uint32_t id_[5] = {1, 1, 1, 1, 1};
        if (!in_defs.empty())
            for (uint32_t ax = 0; ax < irank; ax++) id_[ax] = in_defs[0].dims[ax];
        size_t in_strides[5] = {1, 1, 1, 1, 1};
        for (int d = 3; d >= 0; d--) in_strides[d] = in_strides[d + 1] * id_[d + 1];
        /* axes: param 元素数(维积); 缺省 = 全轴 */
        size_t n_axes = 0;
        if (axes && in_defs.size() > 1) {
            n_axes = 1;
            for (uint32_t d = 0; d < in_defs[1].rank && d < 5; ++d)
                n_axes *= in_defs[1].dims[d];
        }
        bool red[5] = {false, false, false, false, false};
        bool have_axes = (axes != nullptr && n_axes > 0);
        if (have_axes) {
            for (size_t k = 0; k < n_axes; k++) {
                int ax = (int)axes[k];
                if (ax < 0) ax += (int)irank;
                if (ax >= 0 && ax < (int)irank) red[ax] = true;
            }
        } else {
            for (uint32_t ax = 0; ax < irank; ax++) red[ax] = true;
        }
        uint32_t orank = out_def.rank;
        if (orank > 5) orank = 5;
        uint32_t od[5] = {1, 1, 1, 1, 1};
        for (uint32_t ax = 0; ax < orank; ax++) od[ax] = out_def.dims[ax];
        size_t out_strides[5] = {1, 1, 1, 1, 1};
        for (int d = 3; d >= 0; d--) out_strides[d] = out_strides[d + 1] * od[d + 1];
        bool is_sum = (rt == "ReduceSum");
        bool is_mean = (rt == "ReduceMean");
        bool is_max = (rt == "ReduceMax");
        bool is_min = (rt == "ReduceMin");
        if (!(is_sum || is_mean || is_max || is_min)) {
            for (size_t i = 0; i < n; ++i) out[i] = in0[i];  /* 未知 reduce → 直通 */
            return;
        }
        /* 输出坐标 → 输入基址(非 reduce 维) */
        for (size_t i = 0; i < n; i++) {
            size_t rem = i;
            size_t base = 0;
            uint32_t oax = 0;
            for (uint32_t d = 0; d < irank; d++) {
                if (red[d]) continue;
                size_t c = (oax < orank) ? (rem / out_strides[oax]) : 0;
                if (oax < orank) rem %= out_strides[oax];
                oax++;
                base += c * in_strides[d];
            }
            /* 枚举 reduce 维 */
            size_t cnt = 1;
            for (uint32_t d = 0; d < irank; d++) if (red[d]) cnt *= id_[d];
            float acc = is_max ? -INFINITY : (is_min ? INFINITY : 0.0f);
            size_t rrem = 0;
            for (size_t r = 0; r < cnt; r++) {
                rrem = r;
                size_t src = base;
                for (uint32_t d = 0; d < irank; d++) {
                    if (!red[d]) continue;
                    size_t c = rrem % id_[d];
                    rrem /= id_[d];
                    src += c * in_strides[d];
                }
                float v = in0[src];
                if (is_max) acc = (v > acc) ? v : acc;
                else if (is_min) acc = (v < acc) ? v : acc;
                else acc += v;
            }
            if (is_mean) acc /= (float)cnt;
            out[i] = acc;
        }
    } else if (op_type_name == "ScatterNd" || op_type_name == "ScatterND") {
        // ScatterND: out = data(零面); indices [.., K] 前 K 维坐标,
        // updates [.., block] 每坐标一块写入(无 reduction 覆盖语义)。
        // GDN chunk gated delta rule: 每头 (h,0,0) 坐标写 [64,128] 块。
        const float* data = inputs.size() > 0 ? reinterpret_cast<const float*>(inputs[0]) : nullptr;
        const int32_t* idxs = inputs.size() > 1 ? reinterpret_cast<const int32_t*>(inputs[1]) : nullptr;
        const float* upd = inputs.size() > 2 ? reinterpret_cast<const float*>(inputs[2]) : nullptr;
        for (size_t i = 0; i < n; ++i) out[i] = data ? data[i] : 0.0f;
        if (!idxs || !upd) return;
        /* K = indices 末维; n_idx = 前导维积; block = updates/n_idx */
        uint32_t K = 1;
        size_t n_idx = 1;
        if (in_defs.size() > 1 && in_defs[1].rank >= 1) {
            K = in_defs[1].dims[in_defs[1].rank - 1];
            for (uint32_t d = 0; d + 1 < in_defs[1].rank; ++d)
                n_idx *= in_defs[1].dims[d];
        }
        if (K == 0 || K > 5) K = 1;
        if (n_idx == 0) n_idx = 1;
        size_t block = 1;
        if (in_defs.size() > 2) {
            block = 1;
            for (uint32_t d = 0; d < in_defs[2].rank && d < 5; ++d)
                block *= in_defs[2].dims[d];
            block /= n_idx;
        }
        if (block == 0) block = n / n_idx;
        uint32_t rank = out_def.rank;
        if (rank > 5) rank = 5;
        uint32_t od[5] = {1, 1, 1, 1, 1};
        for (uint32_t ax = 0; ax < rank; ax++) od[ax] = out_def.dims[ax];
        size_t ostr[5] = {1, 1, 1, 1, 1};
        for (int d = 3; d >= 0; d--) ostr[d] = ostr[d + 1] * od[d + 1];
        for (size_t e = 0; e < n_idx; e++) {
            size_t base = 0;
            bool bad = false;
            for (uint32_t k = 0; k < K; k++) {
                int c = (int)idxs[e * K + k];
                if (c < 0 || c >= (int)od[k]) { bad = true; break; }
                base += (size_t)c * ostr[k];
            }
            if (bad || base + block > n) continue;
            for (size_t b = 0; b < block; b++) out[base + b] = upd[e * block + b];
        }
    } else if (op_type_name == "Split") {
        // Split(host 参考): 输入沿 axis(缺省末维)等段切; 本副本取
        // split_index 段(loader 注入)。n = 本段元素数。
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        auto sp3 = unpack_scalar_params(params);
        int split_index = 0;
        if (const ScalarParam* p = scalar_get(sp3, "split_index"))
            split_index = (int)(p->is_numeric ? p->value_num
                                              : std::strtol(p->value_str.c_str(), nullptr, 10));
        if (!in0 || in_defs.empty()) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; }
        else {
            uint32_t ar = in_defs[0].rank;
            while (ar > 0 && in_defs[0].dims[ar - 1] == 1) ar--;
            size_t in_axis_len = (ar >= 1) ? in_defs[0].dims[ar - 1] : 1;
            if (in_axis_len == 0) in_axis_len = 1;
            size_t outer = n > 0 ? 0 : 0;
            size_t in_n = 1;
            for (uint32_t d = 0; d < ar; d++) in_n *= in_defs[0].dims[d];
            outer = in_n / in_axis_len;
            size_t seg_len = n / (outer ? outer : 1);
            size_t seg_off = (size_t)split_index * seg_len;
            for (size_t o = 0; o < outer; o++) {
                const float* src = in0 + o * in_axis_len + seg_off;
                for (size_t j = 0; j < seg_len; j++) out[o * seg_len + j] = src[j];
            }
        }
    } else if (op_type_name == "Softmax") {
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        if (!in0) { for (size_t i=0;i<n;++i) out[i]=0; return; }
        /* per-row softmax: 行宽 = axis(缺省末维)维长; 行数 = n/行宽 */
        auto sp4 = unpack_scalar_params(params);
        int axis = -1;
        if (const ScalarParam* p = scalar_get(sp4, "axis"))
            axis = (int)(p->is_numeric ? p->value_num
                                       : std::strtol(p->value_str.c_str(), nullptr, 10));
        uint32_t rk = out_def.rank;
        while (rk > 0 && out_def.dims[rk - 1] == 1) rk--;
        int ax = axis;
        if (ax < 0) ax += (int)rk;
        if (ax < 0 || ax >= (int)rk) ax = (int)rk - 1;
        size_t row_w = (rk > 0) ? out_def.dims[ax] : 1;
        if (row_w == 0) row_w = 1;
        size_t rows = n / row_w;
        for (size_t r = 0; r < rows; r++) {
            float mx = in0[r * row_w];
            for (size_t i = 1; i < row_w; ++i)
                if (in0[r * row_w + i] > mx) mx = in0[r * row_w + i];
            float sum = 0.0f;
            for (size_t i = 0; i < row_w; ++i) {
                out[r * row_w + i] = std::exp(in0[r * row_w + i] - mx);
                sum += out[r * row_w + i];
            }
            if (sum > 0)
                for (size_t i = 0; i < row_w; ++i) out[r * row_w + i] /= sum;
        }
    } else if (op_type_name == "MatMul" || op_type_name == "Dense"
               || op_type_name == "FullyConnected") {
        // MatMul: C[m,n] = A[m,k] @ B[k,n]
        // QNN 4D 填充: 逻辑形状 [m,k] 存为 [m,k,1,...] 或 [1,m,k,1] —
        // "末二维"启发失效; 压掉尾部 1 维得有效 rank, 批维全折
        // (与 extract_matmul_extra / 设备 exec_matmul_f16 同规则)。
        const float* A = inputs.size() > 0 ? reinterpret_cast<const float*>(inputs[0]) : nullptr;
        const float* B = inputs.size() > 1 ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        if (!A || !B) { for (size_t i = 0; i < n; ++i) out[i] = 0.0f; return; }
        auto eff_rank = [](const OutputDef& d) {
            uint32_t r = d.rank;
            while (r > 0 && d.dims[r - 1] == 1) r--;
            return r;
        };
        auto sp = unpack_scalar_params(params);
        uint32_t ork = eff_rank(out_def);
        size_t m = 1;
        for (uint32_t i = 0; i + 1 < ork; i++) m *= out_def.dims[i];
        size_t nn = (ork >= 1) ? out_def.dims[ork - 1] : 1;
        size_t k = 0;
        bool t0 = false, t1 = false;
        /* transpose 判定: scalar 标志优先(None/空串 = 未设置 = 0),
         * 否则形状自洽(converter 的 qkv 预合并 MatMul 无 scalar 标志,
         * B 直接存 [n,k]) */
        if (const ScalarParam* p = scalar_get(sp, "transpose_in1"))
            t1 = p->is_numeric ? (p->value_num != 0)
                               : (!p->value_str.empty() && p->value_str != "0");
        /* FC 语义固定 W 存 [N,K](方阵时形状自洽无法判转置 — probe
         * attn_out W 64×64 实锤; emit 侧 FC 分支同样硬编码 flags=2) */
        if (op_type_name == "FullyConnected") t1 = true;
        if (in_defs.size() > 1) {
            uint32_t br = eff_rank(in_defs[1]);
            if (br >= 2) {
                size_t k_nt = in_defs[1].dims[br - 2], n_nt = in_defs[1].dims[br - 1];
                size_t k_t = n_nt, n_t = k_nt;
                if (!t1 && n_nt != nn && n_t == nn) t1 = true;   /* 形状自洽判转置 */
                k = t1 ? k_t : k_nt;
            } else if (br >= 1) {
                k = in_defs[1].dims[br - 1];
            }
        } else if (in_defs.size() > 0) {
            uint32_t ar = eff_rank(in_defs[0]);
            if (ar >= 1) k = in_defs[0].dims[ar - 1];
        }
        if (k == 0) k = 1;
        if (getenv("GEHTP_EXDIAG")) {
            std::fprintf(stderr, "[mmdiag] m=%zu nn=%zu k=%zu t0=%d t1=%d batched=%d ork=%u A0=%g,%g,%g B0=%g,%g,%g\n",
                         m, nn, k, (int)t0, (int)t1, (int)(ork >= 3 && in_defs.size() > 1), ork,
                         A ? A[0] : -1.f, A ? A[1] : -1.f, A ? A[2] : -1.f,
                         B ? B[0] : -1.f, B ? B[1] : -1.f, B ? B[2] : -1.f);
        }
        /* A 侧转置: A 元素数 = m*k 自洽, 否则试 [k,m] */
        if (in_defs.size() > 0 && m * k > 1) {
            size_t a_n = 1;
            uint32_t ar = eff_rank(in_defs[0]);
            for (uint32_t i = 0; i < ar; i++) a_n *= in_defs[0].dims[i];
            if (a_n != m * k && a_n == nn * k) { t0 = true; std::swap(m, nn); }
        }
        /* batched BMM(attention): A [B,M,K] × B [B,N,K](t1)/[B,K,N] → [B,M,N] */
        bool batched = (ork >= 3 && in_defs.size() > 1);
        if (batched) {
            uint32_t br2 = eff_rank(in_defs[1]);
            if (br2 < 3) batched = false;
            else for (uint32_t i = 0; i + 2 < ork && batched; i++)
                if (out_def.dims[i] != in_defs[1].dims[i]) batched = false;
        }
        if (batched) {
            size_t Bn = 1;
            for (uint32_t i = 0; i + 2 < ork; i++) Bn *= out_def.dims[i];
            size_t M2 = out_def.dims[ork - 2], N2 = out_def.dims[ork - 1];
            for (size_t b = 0; b < Bn; b++)
                for (size_t i = 0; i < M2; i++)
                    for (size_t j = 0; j < N2; j++) {
                        float acc = 0.0f;
                        for (size_t p = 0; p < k; p++) {
                            float av = A[(b * M2 + i) * k + p];
                            float bv = t1 ? B[(b * N2 + j) * k + p] : B[(b * k + p) * N2 + j];
                            acc += av * bv;
                        }
                        out[(b * M2 + i) * N2 + j] = acc;
                    }
        } else {
        for (size_t i = 0; i < m; ++i) {
            for (size_t j = 0; j < nn; ++j) {
                float acc = 0.0f;
                for (size_t p = 0; p < k; ++p) {
                    float av = t0 ? A[(size_t)p * m + i] : A[i * k + p];
                    float bv = t1 ? B[j * k + p] : B[p * nn + j];
                    acc += av * bv;
                }
                out[i * nn + j] = acc;
            }
        }
        }
    } else if (op_type_name == "Conv" || op_type_name == "Conv2d"
               || op_type_name == "DepthWiseConv2d") {
        // Conv2D host reference: NHWC layout
        // inputs[0] = input [N, Hi, Wi, Cin]
        // inputs[1] = weight [Kh, Kw, Cin, Cout] (standard Conv)
        //             or [Kh, Kw, 1, Cin] (depthwise)
        // inputs[2] = bias [Cout] (optional)
        const float* inp    = inputs.size() > 0 ? reinterpret_cast<const float*>(inputs[0]) : nullptr;
        const float* weight = inputs.size() > 1 ? reinterpret_cast<const float*>(inputs[1]) : nullptr;
        const float* bias   = inputs.size() > 2 ? reinterpret_cast<const float*>(inputs[2]) : nullptr;
        if (!inp || !weight) {
            for (size_t i = 0; i < n; ++i) out[i] = 0.0f;
        } else {
            // Extract shapes from in_defs and out_def (rank-4 NHWC)
            size_t N_b = (out_def.rank >= 4) ? out_def.dims[0] : 1;
            size_t Ho  = (out_def.rank >= 4) ? out_def.dims[1] : 1;
            size_t Wo  = (out_def.rank >= 4) ? out_def.dims[2] : 1;
            size_t Cout = (out_def.rank >= 4) ? out_def.dims[3] : out_def.dims[out_def.rank-1];
            size_t Hi = (in_defs.size() > 0 && in_defs[0].rank >= 4) ? in_defs[0].dims[1] : Ho;
            size_t Wi = (in_defs.size() > 0 && in_defs[0].rank >= 4) ? in_defs[0].dims[2] : Wo;
            size_t Cin = (in_defs.size() > 0 && in_defs[0].rank >= 4) ? in_defs[0].dims[3] : 1;
            // Kernel size from weight shape (in_defs[1])
            size_t Kh = (in_defs.size() > 1 && in_defs[1].rank >= 4) ? in_defs[1].dims[0] : 1;
            size_t Kw = (in_defs.size() > 1 && in_defs[1].rank >= 4) ? in_defs[1].dims[1] : 1;
            // Infer stride from shapes: Ho = (Hi - Kh)/sh + 1 => sh = (Hi - Kh)/(Ho - 1)
            size_t sh = (Ho > 1) ? (Hi - Kh) / (Ho - 1) : 1;
            size_t sw = (Wo > 1) ? (Wi - Kw) / (Wo - 1) : 1;
            if (sh == 0) sh = 1;
            if (sw == 0) sw = 1;
            bool is_dw = (op_type_name == "DepthWiseConv2d");
            // Compute pad to center the kernel (same padding)
            int pad_h_num = (int)((Ho - 1) * sh + Kh) - (int)Hi;
            int pad_w_num = (int)((Wo - 1) * sw + Kw) - (int)Wi;
            size_t pad_h = (pad_h_num > 0) ? (size_t)pad_h_num / 2 : 0;
            size_t pad_w = (pad_w_num > 0) ? (size_t)pad_w_num / 2 : 0;

            for (size_t nb = 0; nb < N_b; nb++)
              for (size_t ho = 0; ho < Ho; ho++)
                for (size_t wo = 0; wo < Wo; wo++)
                  for (size_t co = 0; co < Cout; co++) {
                    float acc = bias ? bias[co] : 0.0f;
                    for (size_t kh = 0; kh < Kh; kh++)
                      for (size_t kw = 0; kw < Kw; kw++) {
                        int hi = (int)(ho * sh + kh) - (int)pad_h;
                        int wi = (int)(wo * sw + kw) - (int)pad_w;
                        if (hi < 0 || hi >= (int)Hi || wi < 0 || wi >= (int)Wi) continue;
                        if (is_dw) {
                            // DepthWise: weight[Kh,Kw,1,Cin], Cin==Cout
                            float w = weight[((kh * Kw + kw) * 1 + 0) * Cin + co];
                            float v = inp[((nb * Hi + hi) * Wi + wi) * Cin + co];
                            acc += v * w;
                        } else {
                            // Standard: weight[Kh,Kw,Cin,Cout]
                            for (size_t ci = 0; ci < Cin; ci++) {
                                float w = weight[((kh * Kw + kw) * Cin + ci) * Cout + co];
                                float v = inp[((nb * Hi + hi) * Wi + wi) * Cin + ci];
                                acc += v * w;
                            }
                        }
                      }
                    out[((nb * Ho + ho) * Wo + wo) * Cout + co] = acc;
                  }
        }
    } else {
        // 默认: 直通第一个输入
        const float* in0 = inputs.empty() ? nullptr : reinterpret_cast<const float*>(inputs[0]);
        for (size_t i = 0; i < n; ++i) out[i] = in0 ? in0[i] : 0.0f;
    }
}

// Generic construct: creates a TypicalOp with op type info
// Source: typical_op_prepare.cc, op_registry_prepare.cc:97
// 从 OpDef (io.opdef_ptr) 提取 op_data 参数 blob 存入 op->params，
// 供后续 tiling / 指令选择 / execute 使用。
static std::unique_ptr<Op> generic_construct(const OpIoPtrs& io, op_id_t id, const char* op_name) {
    auto op = std::make_unique<TypicalOp>();
    op->graph = io.graph_prepare;
    if (op_name) op->op_type_name = op_name;
    op->op_id = id;
    if (io.opdef_ptr) {
        const OpDef* opdef = static_cast<const OpDef*>(io.opdef_ptr);
        op->params = opdef->op_data;
        op->cached_out_def = opdef->output_def;
        op->exec_inputs = opdef->inputs;
        // Populate each input connection's source OutputDef so the host
        // reference executor can infer input shapes (needed for MatMul).
        if (io.graph_prepare) {
            for (auto& conn : op->exec_inputs) {
                auto* src_od = io.graph_prepare->get_op_at(conn.src_id);
                if (src_od) conn.src_out_def = src_od->output_def;
            }
        }
        // 指令选择: 根据 op 类型 + dtype + SoC 选 wrapper
        DType dt = static_cast<DType>(opdef->output_def.dtype);
        uint32_t soc = 75;  // 默认 v75; 真实从 env 取
        op->wrapper = select_wrapper(op->op_type_name, dt, soc);
    }
    return op;
}

// All 200+ op constructors delegate to generic_construct for now
// Each would have specific parameter parsing in a full implementation

std::unique_ptr<Op> ConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthWiseConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DilatedConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GroupedConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SparseConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> IndiceConvOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvResidualScalingOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvFusedBiasScaleOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvActivationsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvConvertTransposeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvSpecialEncodingsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MatMulOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DenseOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AddOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SubOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MulOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DivOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MinMaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SquaredDiffOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ElementWiseFloorDivOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ElementWiseSignOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ReluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SigmoidOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TanhOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> EluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GeluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SwishOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HardSigmoidOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HardSwishOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SoftplusOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LeakyReluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PReluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ClampOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LinearClipOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ExpOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SqrtRsqrtOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PowerOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AbsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SinOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AtanOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AsinOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogitOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CeilingOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FloorOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RoundOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> NegOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AvgPoolOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MaxPoolOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BatchNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LayerNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> InstanceNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GroupNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RmsNormOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LrnOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SoftmaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogSoftmaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MaskedSoftmaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LstmOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GruOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ReshapeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TransposeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConcatOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SplitOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FlattenOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ChannelShuffleOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SliceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> StridedSliceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PadOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> MirrorPadOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GatherOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GatherElementsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GatherNdOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ScatterElementsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ScatterNdOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ReduceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ArgMinMaxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CumSumOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }

std::unique_ptr<Op> SelectUnaryOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SelectTernaryOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CastOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FpCastOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> QuantizeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DequantizeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RequantizeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CompareOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> CompareEqualOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogicalOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> LogicalCompareOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SelectOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> IsInfOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> IsNanOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeBilinearOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeNearestOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeTrilinearOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ResizeCubicOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TopKOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> NmsOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> OneHotOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> GridSampleOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RoiAlignOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ExtractGlimpseOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> EinsumOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HadamardOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SwiGluOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ToRgbOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> StftOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SpaceToDepthOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthToSpaceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> FrameToDepthOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthToFrameOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SpaceToBatchOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BatchToSpaceOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RotaryPosEmbdOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RopeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RopeCoeffPackOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BiasAddOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> HashtableLookupOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DecodeBboxOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConvertCenterToCornerOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RandomNormalLikeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> RandomUniformLikeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> BitrearrangeOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> NonZeroOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> AllTrueOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> PartialSumOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> DepthAccumulateOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> WidthToHeightOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> UnpackOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> TileOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConditionalOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> ConditionalAddOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }
std::unique_ptr<Op> SwitchedOp::construct(const OpIoPtrs& io, op_id_t id) { return generic_construct(io, id, nullptr); }

// Op registration helper
// Source: op_package_registry.cc, op_package_ops_opts_registration.cc
// Must be called explicitly to register all ops (avoids static init ordering issues)
static bool ops_registered = false;

void register_all_ops() {
    if (ops_registered) return;
    ops_registered = true;
    auto& reg = OpRegistry::instance();
        // Conv ops
        reg.register_op_fn("Conv", ConvOp::construct);
        // qnn-onnx-converter 产出的 op type 名为 "Conv2d"(见阶段1实测 net.json)
        reg.register_op_fn("Conv2d", ConvOp::construct);
        reg.register_op_fn("DepthWiseConv2d", DepthWiseConvOp::construct);
        reg.register_op_fn("DilatedConv", DilatedConvOp::construct);
        reg.register_op_fn("GroupedConv", GroupedConvOp::construct);
        reg.register_op_fn("SparseConv", SparseConvOp::construct);
        reg.register_op_fn("IndiceConv", IndiceConvOp::construct);
        reg.register_op_fn("ConvResidualScaling", ConvResidualScalingOp::construct);
        reg.register_op_fn("ConvFusedBiasScale", ConvFusedBiasScaleOp::construct);
        reg.register_op_fn("ConvActivations", ConvActivationsOp::construct);
        reg.register_op_fn("ConvConvertTranspose", ConvConvertTransposeOp::construct);
        reg.register_op_fn("ConvSpecialEncodings", ConvSpecialEncodingsOp::construct);
        // MatMul
        reg.register_op_fn("MatMul", MatMulOp::construct);
        reg.register_op_fn("Dense", DenseOp::construct);
        // QNN 2.48 实测 op type 名(M1, 0.8B net.json 20 型差集):
        // FullyConnected=投影层(Dense 语义); CumulativeSum(注册名 "CumSum" 的 QNN 名);
        // Eltwise_Unary/ElementWiseNeuron/Eltwise_Ternary 的 operation 由
        // scalar_params 决定(execute 时从 params 解析)
        reg.register_op_fn("FullyConnected", DenseOp::construct);
        reg.register_op_fn("CumulativeSum", CumSumOp::construct);
        reg.register_op_fn("Eltwise_Unary", SelectUnaryOp::construct);
        reg.register_op_fn("ElementWiseNeuron", SelectUnaryOp::construct);
        reg.register_op_fn("Eltwise_Ternary", SelectTernaryOp::construct);
        // Elementwise
        reg.register_op_fn("Add", AddOp::construct);
        // converter 的二元逐元素 op 类型名(2.48 实测 "Eltwise_Binary";旧版别名)
        reg.register_op_fn("Eltwise_Binary", AddOp::construct);
        reg.register_op_fn("ElementWiseBinary", AddOp::construct);
        reg.register_op_fn("Sub", SubOp::construct);
        reg.register_op_fn("Mul", MulOp::construct);
        reg.register_op_fn("Div", DivOp::construct);
        reg.register_op_fn("MinMax", MinMaxOp::construct);
        reg.register_op_fn("SquaredDifference", SquaredDiffOp::construct);
        reg.register_op_fn("ElementWiseFloorDiv", ElementWiseFloorDivOp::construct);
        reg.register_op_fn("ElementWiseSign", ElementWiseSignOp::construct);
        // Activations
        reg.register_op_fn("Relu", ReluOp::construct);
        reg.register_op_fn("Sigmoid", SigmoidOp::construct);
        reg.register_op_fn("Tanh", TanhOp::construct);
        reg.register_op_fn("Elu", EluOp::construct);
        reg.register_op_fn("Gelu", GeluOp::construct);
        reg.register_op_fn("Swish", SwishOp::construct);
        reg.register_op_fn("HardSigmoid", HardSigmoidOp::construct);
        reg.register_op_fn("HardSwish", HardSwishOp::construct);
        reg.register_op_fn("Softplus", SoftplusOp::construct);
        reg.register_op_fn("LeakyRelu", LeakyReluOp::construct);
        reg.register_op_fn("PRelu", PReluOp::construct);
        reg.register_op_fn("Clamp", ClampOp::construct);
        reg.register_op_fn("LinearClip", LinearClipOp::construct);
        // Math
        reg.register_op_fn("Exp", ExpOp::construct);
        reg.register_op_fn("Log", LogOp::construct);
        reg.register_op_fn("Sqrt", SqrtRsqrtOp::construct);
        reg.register_op_fn("Rsqrt", SqrtRsqrtOp::construct);
        reg.register_op_fn("Power", PowerOp::construct);
        reg.register_op_fn("Abs", AbsOp::construct);
        reg.register_op_fn("Sin", SinOp::construct);
        reg.register_op_fn("Cos", SinOp::construct);
        reg.register_op_fn("Atan", AtanOp::construct);
        reg.register_op_fn("Asin", AsinOp::construct);
        reg.register_op_fn("Logit", LogitOp::construct);
        reg.register_op_fn("Ceiling", CeilingOp::construct);
        reg.register_op_fn("Floor", FloorOp::construct);
        reg.register_op_fn("Round", RoundOp::construct);
        reg.register_op_fn("Neg", NegOp::construct);
        // Pooling
        reg.register_op_fn("AvgPool", AvgPoolOp::construct);
        reg.register_op_fn("MaxPool", MaxPoolOp::construct);
        // Normalization
        reg.register_op_fn("BatchNorm", BatchNormOp::construct);
        reg.register_op_fn("LayerNorm", LayerNormOp::construct);
        reg.register_op_fn("InstanceNorm", InstanceNormOp::construct);
        reg.register_op_fn("GroupNorm", GroupNormOp::construct);
        reg.register_op_fn("RmsNorm", RmsNormOp::construct);
        reg.register_op_fn("Lrn", LrnOp::construct);
        // Softmax
        reg.register_op_fn("Softmax", SoftmaxOp::construct);
        reg.register_op_fn("LogSoftmax", LogSoftmaxOp::construct);
        reg.register_op_fn("MaskedSoftmax", MaskedSoftmaxOp::construct);
        // RNN
        reg.register_op_fn("Lstm", LstmOp::construct);
        reg.register_op_fn("Gru", GruOp::construct);
        // Shape
        reg.register_op_fn("Reshape", ReshapeOp::construct);
        reg.register_op_fn("Transpose", TransposeOp::construct);
        reg.register_op_fn("Concat", ConcatOp::construct);
        reg.register_op_fn("Split", SplitOp::construct);
        reg.register_op_fn("Flatten", FlattenOp::construct);
        reg.register_op_fn("ChannelShuffle", ChannelShuffleOp::construct);
        // Slice/Pad
        reg.register_op_fn("Slice", SliceOp::construct);
        reg.register_op_fn("StridedSlice", StridedSliceOp::construct);
        reg.register_op_fn("Pad", PadOp::construct);
        reg.register_op_fn("MirrorPad", MirrorPadOp::construct);
        // Gather/Scatter
        reg.register_op_fn("Gather", GatherOp::construct);
        reg.register_op_fn("GatherElements", GatherElementsOp::construct);
        reg.register_op_fn("GatherNd", GatherNdOp::construct);
        reg.register_op_fn("ScatterElements", ScatterElementsOp::construct);
        reg.register_op_fn("ScatterNd", ScatterNdOp::construct);
        // Reduction
        reg.register_op_fn("Reduce", ReduceOp::construct);
        reg.register_op_fn("ArgMin", ArgMinMaxOp::construct);
        reg.register_op_fn("ArgMax", ArgMinMaxOp::construct);
        reg.register_op_fn("CumSum", CumSumOp::construct);
        // Cast/Quantize
        reg.register_op_fn("Cast", CastOp::construct);
        reg.register_op_fn("FpCast", FpCastOp::construct);
        reg.register_op_fn("Quantize", QuantizeOp::construct);
        reg.register_op_fn("Dequantize", DequantizeOp::construct);
        reg.register_op_fn("Requantize", RequantizeOp::construct);
        // Compare
        reg.register_op_fn("Compare", CompareOp::construct);
        reg.register_op_fn("CompareEqual", CompareEqualOp::construct);
        reg.register_op_fn("LogicalAnd", LogicalOp::construct);
        reg.register_op_fn("LogicalOr", LogicalOp::construct);
        reg.register_op_fn("LogicalNot", LogicalOp::construct);
        reg.register_op_fn("LogicalXor", LogicalOp::construct);
        reg.register_op_fn("LogicalCompare", LogicalCompareOp::construct);
        reg.register_op_fn("Select", SelectOp::construct);
        reg.register_op_fn("IsInf", IsInfOp::construct);
        reg.register_op_fn("IsNan", IsNanOp::construct);
        // Resize
        reg.register_op_fn("ResizeBilinear", ResizeBilinearOp::construct);
        reg.register_op_fn("ResizeNearest", ResizeNearestOp::construct);
        reg.register_op_fn("ResizeTrilinear", ResizeTrilinearOp::construct);
        reg.register_op_fn("ResizeCubic", ResizeCubicOp::construct);
        // Other
        reg.register_op_fn("TopK", TopKOp::construct);
        reg.register_op_fn("NMS", NmsOp::construct);
        reg.register_op_fn("OneHot", OneHotOp::construct);
        reg.register_op_fn("GridSample", GridSampleOp::construct);
        reg.register_op_fn("RoiAlign", RoiAlignOp::construct);
        reg.register_op_fn("ExtractGlimpse", ExtractGlimpseOp::construct);
        reg.register_op_fn("Einsum", EinsumOp::construct);
        reg.register_op_fn("Hadamard", HadamardOp::construct);
        reg.register_op_fn("SwiGlu", SwiGluOp::construct);
        reg.register_op_fn("ToRgb", ToRgbOp::construct);
        reg.register_op_fn("Stft", StftOp::construct);
        // Space/Depth
        reg.register_op_fn("SpaceToDepth", SpaceToDepthOp::construct);
        reg.register_op_fn("DepthToSpace", DepthToSpaceOp::construct);
        reg.register_op_fn("FrameToDepth", FrameToDepthOp::construct);
        reg.register_op_fn("DepthToFrame", DepthToFrameOp::construct);
        reg.register_op_fn("SpaceToBatch", SpaceToBatchOp::construct);
        reg.register_op_fn("BatchToSpace", BatchToSpaceOp::construct);
        // Attention/RoPE
        reg.register_op_fn("RotaryPosEmbd", RotaryPosEmbdOp::construct);
        reg.register_op_fn("Rope", RopeOp::construct);
        reg.register_op_fn("RopeCoeffPack", RopeCoeffPackOp::construct);
        // Misc
        reg.register_op_fn("BiasAdd", BiasAddOp::construct);
        reg.register_op_fn("HashtableLookup", HashtableLookupOp::construct);
        reg.register_op_fn("DecodeBbox", DecodeBboxOp::construct);
        reg.register_op_fn("ConvertCenterToCorner", ConvertCenterToCornerOp::construct);
        reg.register_op_fn("RandomNormalLike", RandomNormalLikeOp::construct);
        reg.register_op_fn("RandomUniformLike", RandomUniformLikeOp::construct);
        reg.register_op_fn("Bitrearrange", BitrearrangeOp::construct);
        reg.register_op_fn("NonZero", NonZeroOp::construct);
        reg.register_op_fn("AllTrue", AllTrueOp::construct);
        reg.register_op_fn("PartialSum", PartialSumOp::construct);
        reg.register_op_fn("DepthAccumulate", DepthAccumulateOp::construct);
        reg.register_op_fn("WidthToHeight", WidthToHeightOp::construct);
        reg.register_op_fn("Unpack", UnpackOp::construct);
        reg.register_op_fn("Tile", TileOp::construct);
        // Conditional/Switch
        reg.register_op_fn("Conditional", ConditionalOp::construct);
        reg.register_op_fn("ConditionalAdd", ConditionalAddOp::construct);
        reg.register_op_fn("Switched", SwitchedOp::construct);

    // HLX/HMX ops
    register_hlx_hmx_ops();
}

} // namespace hnnx
